### ISSUE TITLE
V.429 dev is giving errors.

### ISSUE THREAD

**Issue by TheIntelloBox** [ProtocolSupport/ProtocolSupport#1002]
Hello ! 🗡 

Here is my error ! :D 

[18:13:05] [Server thread/ERROR]: Could not pass event WorldInitEvent to ProtocolSupport v4.29-dev
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.PlayerList.d()I
	at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTracker.<init>(SpigotEntityTracker.java:65) ~[?:?]
	at protocolsupport.zplatform.impl.spigot.injector.SpigotEntityTrackerInjector.onWorldInit(SpigotEntityTrackerInjector.java:16) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-488]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Thanks for fixing it ! :D 
TheIntelloBox. :D

**Comment by Shevchik** [comment]
Update to latest dev build first. Source lines in exception log doesn't match current.

**Comment by magicus** [comment]
This is likely to be fixed by https://github.com/ProtocolSupport/ProtocolSupport/pull/992. I had the same issue, but the latest version of master solved it. (This is unfortunately not merged into mcpenew yet).

**Comment by TheIntelloBox** [comment]
Can you tag me when the issue is fixed ? I really need this.

**Comment by Artuto** [comment]
Its already fixed, you have to update your PS build.
