### ISSUE TITLE
Error java -  Console 1.13.2

### ISSUE THREAD

**Issue by Guest1131** [ProtocolSupport/ProtocolSupport#1011]
Hi, I noticed that there is a problem, when I enter the server, not always, but at random, appears this error in the console : 

https://pastebin.com/Q5fCYkp7

And I noticed another problem, that there is only with the object "Torch", if I place the torch in the map, when I leave the server, and return, the torch and disappeared, there is no more.

What about a protocol support problem or something else?

Using spigot 1.13.2

Using the latest ProtocolSupport build

**Comment by Shevchik** [comment]
That is not a full exception.

**Comment by Guest1131** [comment]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:27) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-f56e2e7-0c715b3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Shevchik** [comment]
That still doesn't show the exception and message itself.

**Comment by Guest1131** [comment]
In the console, only the one

**Comment by Guest1131** [comment]
Screen console error : 

https://ibb.co/SvfcD6q

The error does not appear immediately, but appears only after, that a player connects to the server.

**Comment by Shevchik** [comment]
Then attach your server log.

**Comment by Guest1131** [comment]
Server log : 

[latest.log](https://github.com/ProtocolSupport/ProtocolSupport/files/2770726/latest.log)

**Comment by colinrgodsey** [comment]
ViaVersion error. Why even use ViaVersion if you're running 1.13.2 ? Confused.

**Comment by Guest1131** [comment]
That mistake gives it, even without ViaVersion.

And in the error there is written protocolsupport.

**Comment by colinrgodsey** [comment]
Update Spigot to the newest version (important), remove ViaVersion, and post that stack trace if it still happens.

**Comment by Shevchik** [comment]
ViaVersion error, you aren't even supposed to run them together when running on latest server.
