### ISSUE TITLE
Forge client cant render 1.13.2 server.

### ISSUE THREAD

**Issue by Zilacon** [ProtocolSupport/ProtocolSupport#1024]
So im using Protocol Support on the latest build of Paper (Build 522) and latest build of PS (Build 355) just recently updated to see if this problem has been fixed or not and it hasn't. Basically I WAS using my former 1.12.2 minecraft server as the HUB for all of my servers on my network (1.7.10/1.10.2/1.12.2) which are all modpacks. On 1.12.2 a client could connect and render the entire spawn fine, there was no issues with PS.

Now... This is what my modpack on 1.7.10 looks like when you join the 1.13.2 server:
![screenshot_45](https://user-images.githubusercontent.com/3002248/52640200-c9f2ae00-2e8a-11e9-9595-da701deff6ed.png)

Your client will continue bouncing up and down and you are unable to move at all, until eventually (like 15 seconds) your client just crashes.

Using another modpack like Tekkit Legends this does not seem to be a problem. Is there a mod in my pack that PS does not support? If so do you know which one it is?
Mod List in Modpack:
![screenshot_46](https://user-images.githubusercontent.com/3002248/52640793-31f5c400-2e8c-11e9-86cf-def01e3b70e8.png)

The spawn being used is built with blocks available on 1.5.2 as we have 1.5.2 servers as well, and the spawn is copied/pasted onto every server on 1.5.2, 1.6.4, 1.7.10, 1.10.2, 1.12.2, 1.13.2. So since the blocks exist in all of these versions for spawn, and there isnt any blocks for later versions that would conflict with older versions. The spawn should appear normally on any version between 1.5.x-1.13.x.

Do you know of any way to fix this?
Joining with normal vanilla on 1.7.10 works fine.
Modpack used: APOC Tech & RPG http://bit.ly/2qdShkZ

**Comment by Shevchik** [comment]
Do a binary search (removing half the mods until issue disappears, and then checking the other half and so on) to find the mod.

**Comment by Zilacon** [comment]
So after removing half of the client side mods, and the problem persisted, i removed the other cluster of client side mods. And now the vanilla server will not even let me join, i just get this:

```
[14:39:44 INFO]: UUID of player Zilacon is 43e54f6c-47d2-43cf-a133-cf020a5d337b
[14:39:45 INFO]: Zilacon[/***.***.***.***:59311] logged in with entity id 3386 at ([Spawn]-4.058117718446304, 49.0, 5.08175242353366)
[14:39:45 ERROR]: Couldn't register custom payload
java.lang.IllegalStateException: Cannot register channel 'l:bc-core'. Too many channels registered!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518) ~[patched_1.13.2.jar:git-Paper-522]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.addChannel(CraftPlayer.java:1457) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2610) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-522]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-522]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-522]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[14:39:45 INFO]: Zilacon lost connection: Invalid payload REGISTER!
[14:39:45 INFO]: [mcMMO] Aborting profile loading recovery for Zilacon - player logged out
```

Im guessing its talking about BuildCraft? But this was not an issue before with the other mods installed so im quite fuzzled...

Any ideas around this? Or do i have to remove BuildCraft to continue?

**Comment by Shevchik** [comment]
You need to disable custom payload channels limit that is built-in into the server.

**Comment by Zilacon** [comment]
Ok after some googlefu i found a work around for that issue by adding ``-Dpaper.disableChannelLimit=true`` to my start up parameters. And even after removing all client side mods and buildcraft the issue is still there. So the search continues.

**Comment by Zilacon** [comment]
Found it ``NotEnoughIDs-1.4.3.4.jar``
Which is a VERY IMPORTANT mod for the pack as the pack is so large without this it just crashes as it hits the block/item limit.

Any way to add support for this mod?
@Shevchik

**Comment by Zilacon** [comment]
Heres the link to it: https://minecraft.curseforge.com/projects/notenoughids

**Comment by Shevchik** [comment]
This mod essentially replaces how blocks and items are encoded and packets format.
Which essentially means that it is not 1.7.10 anymore.

**Comment by Zilacon** [comment]
@Shevchik https://github.com/fewizz/NotEnoughIDs/issues/85
The dev of notenoughids made a version of protocolsupport that works. Could you add support for this version in future releases for this mod?

**Comment by Shevchik** [comment]
Supporting non vanilla protocols and modifications is out of score of this project.
Also the provided version doesn't work with vanilla 1.7.10.
