### ISSUE TITLE
Using certain mob spawn eggs crashes users and the server

### ISSUE THREAD

**Issue by dextonanderson** [ProtocolSupport/ProtocolSupport#1094]
I have noticed that when using a Pig spawn egg with the entity type set to `minecraft:painting`, it is possible to crash users when placing them in mob spawners or crash the server by dispensing them from dispensers.

How to reproduce:

1. Be running a CraftBukkit (spigot/paper/etc) 1.13.2 server.
2. Be running ProtocolSupport build 377 (the latest as of now).
3. Get a spawn egg: `/give @p minecraft:pig_spawn_egg{EntityTag:{id:"minecraft:painting"}} 1`
4. Place the spawn egg in a dispenser and dispense it (this will crash the server) OR place the spawn egg into a mob spawner (this will crash users)

![](https://i.imgur.com/sm2t8xD.png)

When not running ProtocolSupport, and you attempt to use these eggs, the following Exception occurs:
```[10:32:57 FATAL]: Error executing task
net.minecraft.server.v1_13_R2.ReportedException: Saving entity NBT
        at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1692) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:232) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityTypes.b(EntityTypes.java:209) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityTypes.spawnCreature(EntityTypes.java:173) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:168) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:162) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.ItemMonsterEgg.a(SourceFile:81) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:191) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:532) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-626]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_13_R2.EntityHanging.b(EntityHanging.java:223) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.EntityPainting.b(EntityPainting.java:60) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.Entity.save(Entity.java:1655) ~[patched_1.13.2.jar:git-Paper-626]
        ... 20 more
```
Build info:
`protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.04.09 at 18:42:11 MSK, buildhost: build.true-games.org, buildnumber: 377)`
Server platform:
`This server is running Paper version git-Paper-626 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**Comment by Brokkonaut** [comment]
This does not look like a ProtocolSupport bug, but like a server bug

**Comment by dextonanderson** [comment]
It seems to only happen when ProtocolSupport is enabled

**Comment by dextonanderson** [comment]
Is anyone able to reproduce this? It's quite easy to crash a server if you are given access to creative mode.

**Comment by Shevchik** [comment]
Crashes even without protocolsupport installed.

**Comment by dextonanderson** [comment]
Interesting, I couldn't replicate it without PS installed

**Comment by dextonanderson** [comment]
Apologies, this was a vanilla bug. Posting this here in case anyone else has this issue.

https://bugs.mojang.com/browse/MC-154239
https://hub.spigotmc.org/jira/browse/SPIGOT-5054
https://github.com/PaperMC/Paper/pull/2155
