### ISSUE TITLE
1.14.1: Client gets kicked when breaking blocks

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#1098]
When breaking several blocks within a short time, the client gets kicked.

For example in a field with much long grass and the player must be in survival mode - when the player is now breaking several of the long grasses within a short time (left mouse button pressed and look around) he gets kicked.

Debug log: https://pastebin.com/raw/sV4WhcsG

**Comment by Brokkonaut** [comment]
I did some investigations here - The server is sending a SingleBlockChange-Packet with an y value of 4095 (or -1 if its signed, because the value has a size of 12 bits) - 4095 is far outside of the max world height, so this could either be an error by the server or it could be some special value. I do not know if the client just ignores it or does some action on it.

For testing I added a check to MiddleBlockChangeSingle to ignore that y value (https://github.com/Brokkonaut/ProtocolSupport/commit/4674b334bd1133eda5b579170e09a517515bbd36) - I did not see any negative effects on my server and clients will no longer get kicked for breaking blocks. But I'm not sure if that is the correct handling of it.

**Comment by Shevchik** [comment]
Some other plugins also push shitty values there. I guess we should just filter all coords > 256 everywhere (and do it on packet processing level i guess (so wrong coords aren't even sent)).

**Comment by Brokkonaut** [comment]
This causes it (line numbers from the paper server) - The client sends a y=-1 (why ever) and the server thinks it is a valid coordinate.

> [05:42:11 INFO]: BlockPosition{x=394, y=-1, z=-221}
[05:42:11 WARN]: java.lang.Exception
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayOutBlockChange.<init>(PacketPlayOutBlockChange.java:17)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974)
[05:42:11 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[05:42:11 WARN]:        at java.lang.Thread.run(Unknown Source)
