### ISSUE TITLE
End of Stream if warp

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupport#110]
1.5.2 client Crash to click warp menu End of stream

http://pastebin.com/mf4BFSL5

**Comment by Shevchik** [comment]
Need to reproduce this gain, this error log tells nothing useful.

**Comment by swan201** [comment]
[13:13:08 INFO]: duswn[/49.143.112.85:53102] logged in with entity id 1678 at ([
world]-414.5, 66.0, -134.5)
[13:13:08 INFO]: /112.149.97.156:49931 connected with protocol version MINECRAFT
_1_7_10
[13:13:08 WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeExcep
tion: An internal error occured.
[13:13:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(Mes
sageToByteEncoder.java:125)
[13:13:08 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$3.write(NettyChannelInjector.java:268)
[13:13:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[13:13:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[13:13:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[13:13:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[13:13:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[13:13:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[13:13:08 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[13:13:08 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(Net
workManager.java:198)
[13:13:08 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$5$3.run(NettyChannelInjector.java:345)
[13:13:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[13:13:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[13:13:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[13:13:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:13:08 WARN]: Caused by: java.lang.RuntimeException: An internal error occure
d.
[13:13:08 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMetho
dAccessor.invoke(DefaultMethodAccessor.java:20)
[13:13:08 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector.encode(NettyChannelInjector.java:490)
[13:13:08 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$3.encode(NettyChannelInjector.java:262)
[13:13:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(Mes
sageToByteEncoder.java:107)
[13:13:08 WARN]:        ... 14 more
[13:13:08 WARN]: Caused by: java.lang.NullPointerException
[13:13:08 WARN]:        at protocolsupport.protocol.transformer.middlepacket.cli
entbound.play.MiddleSpawnNamed.handle(MiddleSpawnNamed.java:53)
[13:13:08 WARN]:        at protocolsupport.protocol.transformer.v_1_5.PacketEnco
der.encode(PacketEncoder.java:268)
[13:13:08 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.
encode(WrappedEncoder.java:30)
[13:13:08 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.
encode(WrappedEncoder.java:12)
[13:13:08 WARN]:        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown
Source)
[13:13:08 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[13:13:08 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:13:08 WARN]:        at com.comphenix.protocol.reflect.accessors.DefaultMetho
dAccessor.invoke(DefaultMethodAccessor.java:16)
[13:13:08 WARN]:        ... 17 more
[13:13:08 WARN]: java.nio.channels.ClosedChannelException
[13:13:08 WARN]: java.nio.channels.ClosedChannelException
[13:13:08 WARN]: java.nio.channels.ClosedChannelException
[13:13:08 INFO]: duswn lost connection: Internal Exception: io.netty.handler.cod
ec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:13:08 INFO]: [ 섬머서버 ] duswn 님께서 퇴장.

humm... Maybe This issue?

**Comment by Shevchik** [comment]
Not fucking again. Those stupid plugins spawning named entities without adding them to tab...

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
Somethings wrong again?

http://pastebin.com/RP5azH6M

**Comment by Shevchik** [comment]
Should be really fixed now
