### ISSUE TITLE
API version 1.14 breaks 1.13.2 compatibility.

### ISSUE THREAD

**Issue by andrewkm** [ProtocolSupport/ProtocolSupport#1114]
API version 1.14 breaks 1.13.2 compatibility.

`[06:14:53] [Server thread/ERROR]: Could not load 'plugins\ProtocolSupport.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
	at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-632]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]`

**Comment by WesleyVanNeck** [comment]
yeah we only support 1.14.2 @andrewkm

**Comment by yannicklamprecht** [comment]
And why should they support 1.13.2 when you can use an old version for 1.13.2 ?
