### ISSUE TITLE
ConcurrentModificationException in latest ProtocolSupport

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#1159]
This exception occurs sometimes in the log:

[14:29:33] [Server thread/WARN]: [ProtocolSupport] Task #3808051 for ProtocolSupport v4.29-dev generated an exception
java.util.ConcurrentModificationException: null
        at java.util.AbstractList$RandomAccessSpliterator.get(AbstractList.java:737) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:92) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:81) ~[?:?]
        at protocolsupport.zplatform.network.NetworkManagerWrapper$1.run(NetworkManagerWrapper.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[craft103.jar:git-Paper-efabbf13]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[craft103.jar:git-Paper-efabbf13]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[craft103.jar:git-Paper-efabbf13]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[craft103.jar:git-Paper-efabbf13]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[craft103.jar:git-Paper-efabbf13]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[craft103.jar:git-Paper-efabbf13]
        at java.lang.Thread.run(Thread.java:834) [?:?]

[20:07:16 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.14 at 03:04:28 MSK, buildhost: build.true-games.org, buildnumber: 432, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:28b9e96d7c32ebd24db9cb536a987ae10af58982)
[20:07:20 INFO]: This server is running Paper version git-Paper-efabbf13 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Shevchik** [comment]
I guess i should do a defensive copy there.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by Brokkonaut** [comment]
Thanks
