### ISSUE TITLE
ConnectionOpenEvent Error

### ISSUE THREAD

**Issue by YerLocalSenpai** [ProtocolSupport/ProtocolSupport#1170]
[11:55:32] [Netty Server IO #2/ERROR]: Could not pass event ConnectionOpenEvent to ViaVersion v2.1.4-SNAPSHOT
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/server/v1_14_R1/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/server/v1_14_R1/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/server/v1_14_R1/EnumProtocol' }
  Bytecode:
    0x0000000: 2bb6 001a c100 1c99 0034 2bb6 001a c000
    0x0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0x0000020: 2ca6 000a 1db2 0032 9f00 06a7 0010 2ab4
    0x0000030: 0011 b200 38b8 003c b600 422a b400 112a
    0x0000040: b600 46b1
  Stackmap Table:
    append_frame(@43,Object[#28],Integer)
    same_frame(@46)
    chop_frame(@59,2)

        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_221]
        at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator$3.execute(ClassGenerator.java:243) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-065a373-03b145b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot.jar:git-Spigot-065a373-03b145b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:508) [spigot.jar:git-Spigot-065a373-03b145b]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport%20(10).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:28) [ProtocolSupport%20(10).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-065a373-03b145b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:55:32] [Netty Server IO #2/INFO]: [ProtocolSupport] /127.0.0.1:63804 connected with protocol version MINECRAFT_1_14_4
[11:55:39] [Netty Server IO #3/ERROR]: Could not pass event ConnectionOpenEvent to ViaVersion v2.1.4-SNAPSHOT
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/server/v1_14_R1/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/server/v1_14_R1/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/server/v1_14_R1/EnumProtocol' }
  Bytecode:
    0x0000000: 2bb6 001a c100 1c99 0034 2bb6 001a c000
    0x0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0x0000020: 2ca6 000a 1db2 0032 9f00 06a7 0010 2ab4
    0x0000030: 0011 b200 38b8 003c b600 422a b400 112a
    0x0000040: b600 46b1
  Stackmap Table:
    append_frame(@43,Object[#28],Integer)
    same_frame(@46)
    chop_frame(@59,2)

        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_221]
        at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator$3.execute(ClassGenerator.java:243) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-065a373-03b145b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot.jar:git-Spigot-065a373-03b145b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:508) [spigot.jar:git-Spigot-065a373-03b145b]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport%20(10).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-065a373-03b145b]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:28) [ProtocolSupport%20(10).jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [spigot.jar:git-Spigot-065a373-03b145b]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-065a373-03b145b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[11:55:39] [Netty Server IO #3/INFO]: [ProtocolSupport] /127.0.0.1:63815 connected with protocol version MINECRAFT_1_14_4
[11:55:40] [LoginProcessingThread/INFO]: UUID of player YerLocalSenpai is 3d693457-ab67-40cf-ba79-a5debe5cea72
[11:55:40] [Server thread/INFO]: YerLocalSenpai[/127.0.0.1:63815] logged in with entity id 289 at ([world]-142.56504886916122, 68.0, -152.02779931113608)

**Comment by Shevchik** [comment]
Not a protocolsupport issue.
