### ISSUE TITLE
LibsDisguises Error with self viewing disguise

### ISSUE THREAD

**Issue by PhanaticD** [ProtocolSupport/ProtocolSupport#1175]
paper build 209 (1.14.4)
protocolsupport build 437

the following occurs only with protocolsupport enabled, if protocolsupport is removed LibsDisguises works fine

```
[16:05:41 INFO]: PhanaticD issued server command: /d cow
[16:05:41 WARN]: java.lang.NullPointerException
[16:05:41 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.sendSelfDisguise(DisguiseUtilities.java:1554)
[16:05:41 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.setupFakeDisguise(DisguiseUtilities.java:1727)
[16:05:41 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise$2.run(Disguise.java:836)
[16:05:41 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:05:41 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[16:05:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1178)
[16:05:41 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:426)
[16:05:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1105)
[16:05:41 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:932)
[16:05:41 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:05:42 INFO]: PhanaticD issued server command: /u
[16:05:42 WARN]: java.lang.NullPointerException
[16:05:42 WARN]:        at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:1263)
[16:05:42 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:539)
[16:05:42 WARN]:        at me.libraryaddict.disguise.disguisetypes.Disguise.removeDisguise(Disguise.java:480)
[16:05:42 WARN]:        at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:408)
[16:05:42 WARN]:        at me.libraryaddict.disguise.commands.UndisguiseCommand.onCommand(UndisguiseCommand.java:22)
[16:05:42 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:05:42 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[16:05:42 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:740)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1864)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1672)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1036)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1029)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1013)
[16:05:42 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:936)
[16:05:42 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by EOT3000** [comment]
Not related to pspe. If the stack trace contains "protocolsupport", which it doesn't, its not ps's fault. However, it is possible that ps set something to null, in which case it is ps's fault. I'll check it out later

**Comment by Shevchik** [comment]
LibsDisguises tries to find and use some EntityTracker field. Since ps overrides that field, it won't be able to find it. Not sure if that can be fixed.

**Comment by Shevchik** [comment]
Fixed it.
