### ISSUE TITLE
Creating a book causes ProtocolSupport to kick the player

### ISSUE THREAD

**Issue by astei** [ProtocolSupport/ProtocolSupport#1299]
Here is the error:

```
[16:57:27 INFO]: tuxed[/127.0.0.1:43910] logged in with entity id 223 at ([world]179.62392017088393, 63.0, 228.56780087139447)
[16:57:41 WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.11.03 at 03:29:45 UTC, buildhost: ci.velocitypowered.com, buildnumber: 70, buildgit: e04433c23dceadf414a632e585114183584388a1)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: tuxed, originalName: tuxed, uuid: 652a2bc4-e8cd-405d-b7b6-98156ee2dc09, originalUUID: 652a2bc4-e8cd-405d-b7b6-98156ee2dc09, onlinemode: false), player: CraftPlayer{name=tuxed}, address: /127.0.0.1:43910, rawaddress: /0:0:0:0:0:0:0:1%0:43910, version: MINECRAFT_1_16_4))
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:60)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[16:57:41 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:57:41 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:57:41 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[16:57:41 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:57:41 WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:57:41 WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:57:41 WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[16:57:41 WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[16:57:41 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[16:57:41 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[16:57:41 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:57:41 WARN]: Caused by: io.netty.handler.codec.DecoderException: Unable to transform or read serverbound middle packet(data [12, 1, -71, 6, 1, 10, 0, 0, 9, 0, 5, 112, 97, 103, 101, 115, 8, 0, 0, 0, 2, 1, 10, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 0, 12, 97, 119, 114, 119, 102, 101, 114, 103, 103, 104, 103, 104, 8, 0, 5, 116, 105, 116, 108, 101, 0, 1, 97, 8, 0, 6, 97, 117, 116, 104, 111, 114, 0, 5, 116, 117, 120, 101, 100, 0, 1, 2])
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.throwFailedTransformException(AbstractPacketDecoder.java:36)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:27)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:8)
[16:57:41 WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[16:57:41 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:57:41 WARN]: 	... 29 more
[16:57:41 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[16:57:41 WARN]: 	at protocolsupport.protocol.utils.EnumConstantLookups$EnumConstantLookup.getByOrdinal(EnumConstantLookups.java:23)
[16:57:41 WARN]: 	at protocolsupport.protocol.serializer.MiscSerializer.readVarIntEnum(MiscSerializer.java:15)
[16:57:41 WARN]: 	at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_13_14r1_14r2_15_16r1_16r2.EditBook.readClientData(EditBook.java:19)
[16:57:41 WARN]: 	at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode0(ServerBoundMiddlePacket.java:18)
[16:57:41 WARN]: 	at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode(ServerBoundMiddlePacket.java:12)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:31)
[16:57:41 WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:20)
[16:57:41 WARN]: 	... 32 more
```

My server version:
```
This server is running Paper version git-Paper-259 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
```

`/ps buildinfo` reports:
```
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.11.03 at 03:29:45 UTC, buildhost: ci.velocitypowered.com, buildnumber: 70, buildgit: e04433c23dceadf414a632e585114183584388a1)
```

To reproduce, go into creative mode, obtain a book and quill, and then fill 2 pages (just repeating a single character will do) and then sign the book. You will experience the disconnect. I obtained this with Velocity running between the client and the server but this works when I do not have ProtocolSupport installed. I am using vanilla Minecraft 1.16.4.

**Comment by Shevchik** [comment]
Seems that last field of the book edit packet is not a hand anymore, but rather a window slot.

**Comment by Jeremy5762** [comment]
If you give yourself a Book and Quill, open it and just write a backslash in it, and then press "Done", you get kicked with the error message:
`Internal Exception: java.lang.ArrayIndexOutOfBoundsException: 5`

**Comment by Shevchik** [comment]
This was fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/38032669d2ed1b91d05d40c15c5f2f429e06e56a
