### ISSUE TITLE
Players running legacy clients get kicked when >1.16 player gets killed by new mob

### ISSUE THREAD

**Issue by dementisimus** [ProtocolSupport/ProtocolSupport#1304]
ProtocolSupport version: `protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.12.02 at 11:25:17 MSK, buildhost: https://build.true-games.org, buildnumber: 589, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/5bfc6c670ad9ac21b905d4f98c530ff1c57f856e)`
Server version: `git-Paper-259 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`

When Players running legacy clients get kicked when >1.16 player gets killed by new mob

this Exception seems to be thrown @ sending DeathMessage to players

`
   at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:60)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:403)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:154)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
   at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1401)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
   at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:953)
   at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
   at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
   at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
   at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
   at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:312)
   at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
   at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: io.netty.handler.codec.EncoderException: Unable to transform or read clientbound middle packet(type protocolsupport.protocol.packet.middleimpl.clientbound.play.v_8_9r1_9r2_10_11_12r1_12r2_13_14r1_14r2_15.Chat, data [14, -47, 4, 123, 34, 116, 114, 97, 110, 115, 108, 97, 116, 101, 34, 58, 34, 100, 101, 97, 116, 104, 46, 97, 116, 116, 97, 99, 107, 46, 109, 111, 98, 34, 44, 34, 119, 105, 116, 104, 34, 58, 91, 123, 34, 105, 110, 115, 101, 114, 116, 105, 111, 110, 34, 58, 34, 100, 101, 109, 101, 110, 116, 105, 115, 105, 109, 117, 115, 34, 44, 34, 99, 108, 105, 99, 107, 69, 118, 101, 110, 116, 34, 58, 123, 34, 97, 99, 116, 105, 111, 110, 34, 58, 34, 115, 117, 103, 103, 101, 115, 116, 95, 99, 111, 109, 109, 97, 110, 100, 34, 44, 34, 118, 97, 108, 117, 101, 34, 58, 34, 47, 116, 101, 108, 108, 32, 100, 101, 109, 101, 110, 116, 105, 115, 105, 109, 117, 115, 32, 34, 125, 44, 34, 104, 111, 118, 101, 114, 69, 118, 101, 110, 116, 34, 58, 123, 34, 97, 99, 116, 105, 111, 110, 34, 58, 34, 115, 104, 111, 119, 95, 101, 110, 116, 105, 116, 121, 34, 44, 34, 99, 111, 110, 116, 101, 110, 116, 115, 34, 58, 123, 34, 116, 121, 112, 101, 34, 58, 34, 109, 105, 110, 101, 99, 114, 97, 102, 116, 58, 112, 108, 97, 121, 101, 114, 34, 44, 34, 105, 100, 34, 58, 34, 49, 57, 49, 56, 57, 99, 57, 52, 45, 99, 97, 53, 48, 45, 52, 101, 48, 99, 45, 97, 48, 99, 102, 45, 55, 54, 100, 53, 97, 98, 101, 50, 53, 48, 97, 101, 34, 44, 34, 110, 97, 109, 101, 34, 58, 123, 34,
116, 101, 120, 116, 34, 58, 34, 100, 101, 109, 101, 110, 116, 105, 115, 105, 109, 117, 115, 34, 125, 125, 125, 44, 34, 116, 101, 120, 116, 34, 58, 34, 100, 101, 109, 101, 110, 116, 105, 115, 105, 109, 117, 115, 34, 125, 44, 123, 34, 105, 110, 115, 101,
114, 116, 105, 111, 110, 34, 58, 34, 55, 57, 50, 49, 54, 100, 102, 100, 45, 57, 102, 101, 99, 45, 52, 100, 52, 55, 45, 97, 48, 52, 54, 45, 102, 56, 102, 57, 100, 55, 55, 54, 53, 100, 55, 50, 34, 44, 34, 104, 111, 118, 101, 114, 69, 118, 101, 110, 116, 34, 58, 123, 34, 97, 99, 116, 105, 111, 110, 34, 58, 34, 115, 104, 111, 119, 95, 101, 110, 116, 105, 116, 121, 34, 44, 34, 99, 111, 110, 116, 101, 110, 116, 115, 34, 58, 123, 34, 116, 121, 112, 101, 34, 58, 34, 109, 105, 110, 101, 99, 114, 97, 102, 116,
58, 112, 105, 103, 108, 105, 110, 95, 98, 114, 117, 116, 101, 34, 44, 34, 105, 100, 34, 58, 34, 55, 57, 50, 49, 54, 100, 102, 100, 45, 57, 102, 101, 99, 45, 52, 100, 52, 55, 45, 97, 48, 52, 54, 45, 102, 56, 102, 57, 100, 55, 55, 54, 53, 100, 55, 50, 34, 44, 34, 110, 97, 109, 101, 34, 58, 123, 34, 116, 114, 97, 110, 115, 108, 97, 116, 101, 34, 58, 34, 101, 110, 116, 105, 116, 121, 46, 109, 105, 110, 101, 99, 114, 97, 102, 116, 46, 112, 105, 103, 108, 105, 110, 95, 98, 114, 117, 116, 101, 34, 125, 125,
125, 44, 34, 116, 114, 97, 110, 115, 108, 97, 116, 101, 34, 58, 34, 101, 110, 116, 105, 116, 121, 46, 109, 105, 110, 101, 99, 114, 97, 102, 116, 46, 112, 105, 103, 108, 105, 110, 95, 98, 114, 117, 116, 101, 34, 125, 93, 125, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
   at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.write(AbstractPacketEncoder.java:65)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
   at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
   at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:57)
   at protocolsupport.utils.netty.MessageToMessageCodec.write(MessageToMessageCodec.java:61)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
   at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:300)
   ... 6 more
 Caused by: java.lang.NullPointerException
   at protocolsupport.protocol.serializer.chat.LegacyValueHoverActionSerializer.serialize(LegacyValueHoverActionSerializer.java:57)
   at protocolsupport.protocol.serializer.chat.LegacyValueHoverActionSerializer.serialize(LegacyValueHoverActionSerializer.java:32)
   at protocolsupport.protocol.utils.json.SimpleJsonTreeSerializer.serialize(SimpleJsonTreeSerializer.java:39)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serialize(ComponentSerializer.java:175)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serialize(ComponentSerializer.java:183)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serialize(ComponentSerializer.java:27)
   at protocolsupport.protocol.utils.json.SimpleJsonTreeSerializer.serialize(SimpleJsonTreeSerializer.java:39)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serializeAndAdd(ComponentSerializer.java:192)
   at protocolsupport.protocol.serializer.chat.ServerTranslateTranslateComponentContentSerializer.serialize(ServerTranslateTranslateComponentContentSerializer.java:54)
   at protocolsupport.protocol.serializer.chat.ServerTranslateTranslateComponentContentSerializer.serialize(ServerTranslateTranslateComponentContentSerializer.java:15)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serialize(ComponentSerializer.java:187)
   at protocolsupport.protocol.serializer.chat.ComponentSerializer.serialize(ComponentSerializer.java:27)
   at protocolsupport.protocol.utils.json.SimpleJsonTreeSerializer.serialize(SimpleJsonTreeSerializer.java:39)
   at protocolsupport.protocol.serializer.chat.ChatSerializer.serializeTree(ChatSerializer.java:99)
   at protocolsupport.protocol.serializer.chat.ChatSerializer.serialize(ChatSerializer.java:103)
   at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_8_9r1_9r2_10_11_12r1_12r2_13_14r1_14r2_15.Chat.writeToClient(Chat.java:22)
   at protocolsupport.protocol.packet.middle.ClientBoundMiddlePacket.encode0(ClientBoundMiddlePacket.java:23)
   at protocolsupport.protocol.packet.middle.ClientBoundMiddlePacket.encode(ClientBoundMiddlePacket.java:12)
   at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.write(AbstractPacketEncoder.java:54)
   ... 32 more
`

**Comment by TNTUP** [comment]
Can confirm on a 1.12.2 Forge client, 2 months ago

**Comment by Shevchik** [comment]
Which mobs exactly do cause that? I may guess it's all about remap registries missing entries for some entities, or specific combination of entity and protocol version cause that.

**Comment by Cazmon** [comment]
Same problem with the new mobs: hoglin piglin, piglinbrute

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/04834effe2ac0c90a99f2772d372bd696f343cc1

**Comment by Cazmon** [comment]
still happening a java.lang.NullPointerException

**Comment by dementisimus** [comment]
thank you! :D
