### ISSUE TITLE
Java 16 - problem with load plugin

### ISSUE THREAD

**Issue by xCraftRayX** [ProtocolSupport/ProtocolSupport#1329]
Server version: 1.16.5

[11:04:00] [Server thread/ERROR]: [ProtocolSupport] Error when loading, shutting down
java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "$
        at protocolsupport.utils.ReflectionUtils.setStaticFinalField(ReflectionUtils.java:54) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.block.SpigotBlocksBoundsAdjust.inject(SpigotBlocksBoundsAdjust.java:20) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.injector.SpigotPlatformInjector.onLoad(SpigotPlatformInjector.java:12) ~[?:?]
        at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-590]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-590]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.i$
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
        at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
        at protocolsupport.utils.ReflectionUtils.setAccessible(ReflectionUtils.java:12) ~[?:?]
        at protocolsupport.utils.ReflectionUtils.setStaticFinalField(ReflectionUtils.java:49) ~[?:?]
        ... 8 more

**Comment by pkt77** [comment]
Temporary fix - add these to your java parameters: `--illegal-access=warn --add-opens java.base/java.lang.invoke=ALL-UNNAMED`

**Comment by Shevchik** [comment]
This is probably fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/df80677af50842ca4932797d0d5f3870a15c408b at least for JVMs with sun.misc.Unsafe.

**Comment by pkt77** [comment]
Can confirm this is fixed.
