### ISSUE TITLE
>> 1.17

### ISSUE THREAD

**Issue by TheFruxz** [ProtocolSupport/ProtocolSupport#1336]
# Feature Request
## The Arrival

Now the Bukkit/Spigot 1.17-Versions are available, so plugins can be developed for the current minecraft version

## The Request

Can you please develop an update for the 1.17 version of ProtocolSupport?

**Comment by ErythroCraft** [comment]
Hi. I'm same

This is the bug.
[20:23:39] [Server thread/INFO]: [ProtocolSupport] File log is not enabled
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ????????????????????????????????????????????????????????????????????
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?                               ERROR
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   Unsupported platform or version dev-Spigot-66f9d3c-cbf2f67 (MC: 1.17)
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   This version of plugin only supports
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   server minecraft version 1.16.5
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   and following platforms:
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   - Spigot (https://www.spigotmc.org/)
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?   - Paper (https://papermc.io/)
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ?       https://github.com/ProtocolSupport/ProtocolSupport/
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] ????????????????????????????????????????????????????????????????????
[20:23:39] [Server thread/ERROR]: [ProtocolSupport] Platform init failed
java.lang.UnsupportedOperationException: No supported platform detected
        at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:19) ~[?:?]
        at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        Suppressed: java.lang.UnsupportedOperationException: Failed to init spigot platform
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:26) ~[?:?]
                at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:63) ~[?:?]
                at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at java.lang.Thread.run(Thread.java:831) [?:?]
        Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/NetworkManager
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:21) ~[?:?]
                ... 6 more
        Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3.NetworkManager
                at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:dev-Spigot-66f9d3c-cbf2f67]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:21) ~[?:?]
                ... 6 more

**Comment by ErythroCraft** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by pkt77** [comment]
@TheFruxz @ErythroCraft Don't make posts like this, it's very disrespectful. It's obvious a new update came out, updating takes time. You should not pester devs to work on something they are already doing.
