### ISSUE TITLE
Possible bug in 1.17-Dev

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1338]
* ProtocolSupport version (/ps buildinfo)
* protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.06.17 at 00:48:53 MSK, buildhost: https://build.true-games.org, buildnumber: 623, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/ea524d99ecb596f9379efbf3f09d4fd99bf278d8)
* Server version
* This server is running CraftBukkit version 3149-Spigot-101ebb6-9122f5a (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

I using ProtocolSupport in my project and i have if condition for checking if player connect from version 1.17 and for enabling onlinemode for player who have mojang account. Seems like a bug in Dev Version if you know about this bug sorry for report.

My code
```kotlin
        val connection = event.connection
        val playerVersion = ProtocolSupportAPI.getProtocolVersion(connection.player)
        val latestVersion = ProtocolVersion.getLatest(ProtocolType.PC)
        if (playerVersion != ProtocolVersion.getLatest(ProtocolType.PC)) {
            event.denyLogin(amikaCore.replaceMessage(String.format("&cServer support %s, but you have %s", latestVersion, playerVersion)))
            return
        }
```
But method Throw Exception Player can't be null
```java
    @Nullable
    public static Connection getConnection(@Nonnull Player player) {
        Validate.notNull(player, "Player can't be null", new Object[0]);
        Connection connection = ServerPlatform.get().getMiscUtils().getConnection(player);
        return (Connection)(connection != null ? connection : getConnection((SocketAddress)player.spigot().getRawAddress()));
    }
```

Error:
```
[12:35:21] [LoginProcessingThread/ERROR]: Could not pass event PlayerLoginStartEvent to AmikaCore v1.3.3-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener.lambda$handleLoginStart$4(AbstractLoginListener.java:124) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Player can't be null
        at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
        at protocolsupport.libs.org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[?:?]
        at protocolsupport.api.ProtocolSupportAPI.getConnection(ProtocolSupportAPI.java:74) ~[?:?]
        at protocolsupport.api.ProtocolSupportAPI.getProtocolVersion(ProtocolSupportAPI.java:44) ~[?:?]
        at encryptsl.cekuj.net.listeners.PremiumLoginClass.premiumLogin(PremiumLoginClass.kt:19) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
        ... 7 more
```

**Comment by Shevchik** [comment]
WAI. Player instance doesn't exist until player join. The connection has a method to determine the version.

**Comment by EncryptSL** [comment]
Thanks for answer
