### ISSUE TITLE
If try write in book and done this you will be kicked.

### ISSUE THREAD

**Issue by RitaSister** [ProtocolSupport/ProtocolSupport#1346]
[10:55:13] [Netty Epoll Server IO #1/WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: [buildtime=2021.07.10 at 09:19:46 MSK, buildhost=https://build.true-games.org, buildnumber=641, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/3b57ae4efc02a1918673a60cee2ce5e0a23343e8]): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: RitaSister, originalName: RitaSister, uuid: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, originalUUID: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, onlinemode: false), player: CraftPlayer{name=RitaSister}, address: /134.249.196.140:60359, rawaddress: /127.0.0.1:60359, version: MINECRAFT_1_17_1))
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:65)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:454)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataCodecImpl.writeServerboundInternal(PacketDataCodecImpl.java:114)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataCodecImpl$2.read(PacketDataCodecImpl.java:45)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataCodecImpl$ServerBoundPacketDataProcessor.process(PacketDataCodecImpl.java:216)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataCodecImpl.writeServerbound(PacketDataCodecImpl.java:72)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.packet.middle.serverbound.play.MiddleEditBook.write(MiddleEditBook.java:22)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode0(ServerBoundMiddlePacket.java:23)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode(ServerBoundMiddlePacket.java:12)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:31)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:20)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:8)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:23)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:55:13] [Netty Epoll Server IO #1/WARN]: Caused by: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex: 14, writerIndex: 13 (expected: 0 <= readerIndex <= writerIndex <= capacity(4096))
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	... 48 more
[10:55:13] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex: 14, writerIndex: 13 (expected: 0 <= readerIndex <= writerIndex <= capacity(4096))
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.PacketDataSerializer.readerIndex(PacketDataSerializer.java:681)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.PacketDataSerializer.e(PacketDataSerializer.java:561)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBEdit.lambda$new$0(PacketPlayInBEdit.java:32)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.PacketDataSerializer.a(PacketDataSerializer.java:132)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBEdit.<init>(PacketPlayInBEdit.java:32)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.EnumProtocol$a.a(EnumProtocol.java:280)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.EnumProtocol.a(EnumProtocol.java:214)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:34)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:569)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	... 50 more
[10:55:13] [Netty Epoll Server IO #1/WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: [buildtime=2021.07.10 at 09:19:46 MSK, buildhost=https://build.true-games.org, buildnumber=641, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/3b57ae4efc02a1918673a60cee2ce5e0a23343e8]): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: RitaSister, originalName: RitaSister, uuid: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, originalUUID: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, onlinemode: false), player: CraftPlayer{name=RitaSister}, address: /134.249.196.140:60359, rawaddress: /127.0.0.1:60359, version: MINECRAFT_1_17_1))
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:65)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:454)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:23)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:55:13] [Netty Epoll Server IO #1/WARN]: Caused by: io.netty.handler.codec.DecoderException: Unable to transform or read serverbound middle packet(data [11, 0, 1, 1, 49, 0])
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.throwFailedTransformException(AbstractPacketDecoder.java:36)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:27)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:8)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	... 30 more
[10:55:13] [Netty Epoll Server IO #1/WARN]: Caused by: io.netty.handler.codec.DecoderException: Data not read fully, bytes left 2
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:22)
[10:55:13] [Netty Epoll Server IO #1/WARN]: 	... 33 more
[10:55:13] [Server thread/INFO]: RitaSister lost connection: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: [buildtime=2021.07.10 at 09:19:46 MSK, buildhost=https://build.true-games.org, buildnumber=641, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/3b57ae4efc02a1918673a60cee2ce5e0a23343e8]): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: RitaSister, originalName: RitaSister, uuid: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, originalUUID: 80cbac37-2a59-4c5e-8aed-ead1a34ffd6d, onlinemode: false), player: CraftPlayer{name=RitaSister}, address: /134.249.196.140:60359, rawaddress: /127.0.0.1:60359, version: MINECRAFT_1_17_1))

**Comment by Shevchik** [comment]
Book edit packet changed from using itemstack instance to the page list with optional title. Will fix it soon.

**Comment by Shevchik** [comment]
Should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/46abd19308f146cd2d9cc6011de2cceb66df36ed
