### ISSUE TITLE
AIR ItemStack hoverEvent causes players to be kicked with UnsupportedOperationException

### ISSUE THREAD

**Issue by LOOHP** [ProtocolSupport/ProtocolSupport#1350]
ProtocolSupport seems to have problem processing `show_item` hoverEvent with an `AIR` item as content on 1.17.

Steps: 
1. Send the message into chat, like this:
```
/minecraft:tellraw @a {"text": "item", "hoverEvent": {"action": "show_item", "contents": {"id": "minecraft:air"}}}
```
2. The players receiving the message will all be kicked with
```
Internal Exception: java.lang.UnsupportedOperationException: Null itemstack
```

ps buildinfo:
```
[buildtime=2021.07.22 at 11:35:49 MSK, buildhost=https://build.true-games.org, buildnumber=645, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/92a1cc4ee258e0d424ff7cdc773783e6ed60dc44]
```

ps debug
```
[22:39:13 WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: [buildtime=2021.07.22 at 11:35:49 MSK, buildhost=https://build.true-games.org, buildnumber=645, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/92a1cc4ee258e0d424ff7cdc773783e6ed60dc44]): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: LOOHP, originalName: LOOHP, uuid: d26f544b-392a-4a41-891f-fa470f5e6b40, originalUUID: d26f544b-392a-4a41-891f-fa470f5e6b40, onlinemode: false), player: CraftPlayer{name=LOOHP}, address: /127.0.0.1:55329, rawaddress: /127.0.0.1:55329, version: MINECRAFT_1_17_1))
[22:39:13 WARN]:        at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:65)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[22:39:13 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[22:39:13 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:454)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[22:39:13 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
[22:39:13 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
[22:39:13 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
[22:39:13 WARN]:        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
[22:39:13 WARN]:        at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
[22:39:13 WARN]:        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[22:39:13 WARN]:        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[22:39:13 WARN]:        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[22:39:13 WARN]:        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
[22:39:13 WARN]:        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[22:39:13 WARN]:        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[22:39:13 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:326)
[22:39:13 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[22:39:13 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[22:39:13 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[22:39:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[22:39:13 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[22:39:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[22:39:13 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:39:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:39:13 WARN]: Caused by: io.netty.handler.codec.EncoderException: Unable to transform or read clientbound middle packet(type protocolsupport.protocol.packet.middleimpl.clientbound.play.v_16r1_16r2_17r1_17r2.Chat, data [15, 85, 123, 34, 104, 111, 118, 101, 114, 69, 118, 101, 110, 116, 34, 58, 123, 34, 97, 99, 116, 105, 111, 110, 34, 58, 34, 115, 104, 111, 119, 95, 105, 116, 101, 109, 34, 44, 34, 99, 111, 110, 116, 101, 110, 116, 115, 34, 58, 123, 34, 105, 100, 34, 58, 34, 109, 105, 110, 101, 99, 114, 97, 102, 116, 58, 97, 105, 114, 34, 125, 125, 44, 34, 116, 101, 120, 116, 34, 58, 34, 105, 116, 101, 109, 34, 125, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[22:39:13 WARN]:        at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.write(AbstractPacketEncoder.java:64)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:39:13 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:39:13 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[22:39:13 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:39:13 WARN]:        at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:57)
[22:39:13 WARN]:        at protocolsupport.utils.netty.MessageToMessageCodec.write(MessageToMessageCodec.java:61)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[22:39:13 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[22:39:13 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[22:39:13 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[22:39:13 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[22:39:13 WARN]:        ... 8 more
[22:39:13 WARN]: Caused by: java.lang.UnsupportedOperationException: Null itemstack
[22:39:13 WARN]:        at protocolsupport.protocol.types.NetworkItemStack$1.reject(NetworkItemStack.java:67)
[22:39:13 WARN]:        at protocolsupport.protocol.types.NetworkItemStack$1.getTypeId(NetworkItemStack.java:87)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.HoverActionSerializer.serialize(HoverActionSerializer.java:131)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.HoverActionSerializer.serialize(HoverActionSerializer.java:32)
[22:39:13 WARN]:        at protocolsupport.protocol.utils.json.SimpleJsonTreeSerializer.serialize(SimpleJsonTreeSerializer.java:38)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.ComponentSerializer.serialize(ComponentSerializer.java:175)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.ComponentSerializer.serialize(ComponentSerializer.java:27)
[22:39:13 WARN]:        at protocolsupport.protocol.utils.json.SimpleJsonTreeSerializer.serialize(SimpleJsonTreeSerializer.java:38)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.ChatCodec.serializeTree(ChatCodec.java:102)
[22:39:13 WARN]:        at protocolsupport.protocol.codec.chat.ChatCodec.serialize(ChatCodec.java:106)
[22:39:13 WARN]:        at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_16r1_16r2_17r1_17r2.Chat.write(Chat.java:25)
[22:39:13 WARN]:        at protocolsupport.protocol.packet.middle.ClientBoundMiddlePacket.encode0(ClientBoundMiddlePacket.java:23)
[22:39:13 WARN]:        at protocolsupport.protocol.packet.middle.ClientBoundMiddlePacket.encode(ClientBoundMiddlePacket.java:12)
[22:39:13 WARN]:        at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.write(AbstractPacketEncoder.java:53)
[22:39:13 WARN]:        ... 34 more
```

**Comment by yannicklamprecht** [comment]
Something like show item stack type air is stupid, it shouldn't work in the first place.

**Comment by LOOHP** [comment]
I agree that showing air is not very useful, but it is an accepted feature in the vanilla chat system.

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/a98977e7b6d17ecbfb35ee85fe184d0701cd95fc
