### ISSUE TITLE
ProtocolSupport PE not work

### ISSUE THREAD

**Issue by Delimer** [ProtocolSupport/ProtocolSupport#136]
I add last build of ProtokolSupportPE in plugin folder and start server.
`[12:17:51 INFO]: This server is running CraftBukkit version git-Spigot-1544 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[12:17:52 INFO]: Using 4 threads for Netty based IO
[12:17:52 INFO]: Server Ping Player Sample Count: 12
[12:17:52 INFO]: Generating keypair
[12:17:53 INFO]: Starting Minecraft server on *:25565
[12:17:53 INFO]: [ProtocolSupport] Loading ProtocolSupport v4.23.dev
[12:17:53 WARN]: java.lang.NoClassDefFoundError: io/netty/buffer/PooledByteBufAllocator
[12:17:53 WARN]:        at protocolsupport.utils.netty.Allocator.<clinit>(Allocator.java:33)
[12:17:53 WARN]:        at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:22)
[12:17:53 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
[12:17:53 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
[12:17:53 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[12:17:53 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[12:17:53 WARN]: Caused by: java.lang.ClassNotFoundException: io.netty.buffer.PooledByteBufAllocator
[12:17:53 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[12:17:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
[12:17:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[12:17:53 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:17:53 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:17:53 WARN]:        ... 6 more
[12:17:54 INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.23.dev`

**Comment by Shevchik** [comment]
You are not running latest Spgot 1.8.8

**Comment by Delimer** [comment]
Ок. Now start server with protocol support. But problem with MC WIN 10. When I try create logs in inventory client crush, but in MCPE its work fine.

`[13:29:18 INFO]: Done (9.699s)! For help, type "help" or "?"
[13:30:09 FATAL]: java.lang.NullPointerException
[13:30:10 FATAL]: java.lang.NullPointerException
[13:30:10 FATAL]: java.lang.NullPointerException
[13:30:15 FATAL]: java.lang.NullPointerException
[13:30:16 INFO]: BoundenCloth94[/213.85.40.190:57724] logged in with entity id 261 at ([world]155.35409545898438, 72.0, 283.5992126464844)
[13:30:33 INFO]: BoundenCloth94 lost connection: Failed to handle packet: class protocolsupport.protocol.transformer.mcpe.packet.mcpe.serverbound.CraftPacket$1
[13:30:33 INFO]: BoundenCloth94 left the game.`

**Comment by Shevchik** [comment]
Enable debug and post a stactrace here. But probably it is the mcw10 problem.

**Comment by Delimer** [comment]
`[14:36:37 INFO]: Done (10.987s)! For help, type "help" or "?"
[14:36:40 FATAL]: java.lang.NullPointerException
[14:36:42 FATAL]: java.lang.NullPointerException
[14:36:44 INFO]: BoundenCloth94[/213.85.40.190:57724] logged in with entity id 242 at ([world]166.65553283691406, 69.0, 267.9319763183594)
[14:36:58 INFO]: BoundenCloth94 lost connection: Failed to handle packet: class protocolsupport.protocol.transformer.mcpe.packet.mcpe.serverbound.CraftPacket$1
[14:36:58 INFO]: BoundenCloth94 left the game.
[14:36:58 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[14:36:58 WARN]:        at protocolsupport.protocol.transformer.mcpe.packet.mcpe.serverbound.CraftPacket.trim(CraftPacket.java:115)
[14:36:58 WARN]:        at protocolsupport.protocol.transformer.mcpe.packet.mcpe.serverbound.CraftPacket$1.handle0(CraftPacket.java:75)
[14:36:58 WARN]:        at protocolsupport.protocol.transformer.mcpe.packet.mcpe.serverbound.CraftPacket$1.handle0(CraftPacket.java:61)
[14:36:58 WARN]:        at protocolsupport.protocol.transformer.mcpe.packet.HandleNMSPacket.handle(HandleNMSPacket.java:28)
[14:36:58 WARN]:        at protocolsupport.protocol.transformer.mcpe.packet.SynchronizedHandleNMSPacket$1.run(SynchronizedHandleNMSPacket.java:13)
[14:36:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729)
[14:36:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:36:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:36:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:36:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
`

**Comment by Shevchik** [comment]
Client sent nothing as used ingredients. No ingredients - no crafting.

**Comment by Delimer** [comment]
Eh, this is MCW10 bug ((( 
Кстати, по-русски можно писать?
