### ISSUE TITLE
1.4.7 - Crash when hovering on enchanted item (Minecraft has stopped running because it encountered a problem; Reading NBT data)

### ISSUE THREAD

**Issue by Seshpenguin** [ProtocolSupport/ProtocolSupport#1372]
Buildinfo:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/6313946/143155580-40b94e78-b4c0-4dad-bc7d-c66ea82b3624.png">
(Build 661)

Server: PaperMC 1.17.1 git-Paper-388 (only 1 plugin, which is ProtocolSupport)
Minecraft Client Version: 1.4.7 (haven't tested on others yet)

**Opening a chest with some enchanted items (naturally generated ruined portal), hovering over certain items with newer enchantments will cause the game to freeze then crash. Picking up the items is fine, but then hovering over them in your inventory will trigger a crash. It appears using the item will also trigger a crash.**

MC Crash log (no meaningful logs in server console)
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 23/11/21 8:45 PM
Description: Reading NBT data

java.lang.ClassCastException: bp cannot be cast to cb
	at bq.d(SourceFile:116)
	at ur.a(SourceFile:395)
	at avf.a(SourceFile:169)
	at avf.a(SourceFile:142)
	at avv.a(SourceFile:31)
	at avz.a(SourceFile:48)
	at ban.b(SourceFile:774)
	at net.minecraft.client.Minecraft.J(SourceFile:605)
	at net.minecraft.client.Minecraft.run(SourceFile:534)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Corrupt NBT tag --
Details:
	Tag type found: BYTE
	Tag type expected: SHORT
	Tag name: lvl
Stacktrace:
	at bq.d(SourceFile:116)
	at ur.a(SourceFile:395)
	at avf.a(SourceFile:169)
	at avf.a(SourceFile:142)
	at avv.a(SourceFile:31)
	at avz.a(SourceFile:48)

-- Screen render details --
Details:
	Screen name: avz
	Mouse location: Scaled: (212, 180). Absolute: (424, 119)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ays['Seshpenguin'/1189, l='MpServer', x=-4.27, y=66.62, z=146.30]]
	Chunk stats: MultiplayerChunkCache: 397
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options:
	Level spawn location: World: (0,71,168), Chunk: (at 0,4,8 in 0,10; contains blocks 0,0,160 to 15,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10340 game time, 10340 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [ays['Seshpenguin'/1189, l='MpServer', x=-4.27, y=66.62, z=146.30], qn['Skeleton'/1152, l='MpServer', x=7.47, y=43.00, z=186.69], qn['Skeleton'/1153, l='MpServer', x=6.69, y=41.00, z=178.69], ow['Bat'/1155, l='MpServer', x=28.01, y=28.30, z=158.58], ow['Bat'/1157, l='MpServer', x=20.22, y=42.58, z=152.58], ow['Bat'/1095, l='MpServer', x=-15.56, y=61.72, z=185.53], ph['Squid'/841, l='MpServer', x=-8.49, y=37.02, z=137.51], ow['Bat'/1034, l='MpServer', x=-19.56, y=54.46, z=155.50], qp['Spider'/780, l='MpServer', x=5.70, y=41.00, z=146.38], ph['Squid'/1164, l='MpServer', x=29.28, y=52.98, z=143.50], ow['Bat'/1171, l='MpServer', x=13.70, y=49.38, z=158.70], qr['Zombie'/1107, l='MpServer', x=29.50, y=19.00, z=134.78], qn['Skeleton'/1172, l='MpServer', x=4.50, y=40.00, z=179.50], qn['Skeleton'/1173, l='MpServer', x=7.47, y=43.00, z=185.97], ph['Squid'/1178, l='MpServer', x=31.59, y=31.92, z=117.38], ow['Bat'/352, l='MpServer', x=-2.41, y=51.10, z=157.75], ow['Bat'/1057, l='MpServer', x=-26.50, y=47.06, z=189.72], ow['Bat'/930, l='MpServer', x=22.31, y=42.93, z=153.75], ow['Bat'/996, l='MpServer', x=13.45, y=52.90, z=140.61], ow['Bat'/357, l='MpServer', x=14.28, y=43.00, z=144.59], ow['Bat'/358, l='MpServer', x=12.34, y=43.00, z=143.19], ow['Bat'/359, l='MpServer', x=12.22, y=43.00, z=143.97], ow['Bat'/360, l='MpServer', x=12.91, y=43.00, z=143.06], qp['Spider'/1129, l='MpServer', x=23.15, y=58.39, z=172.62], ow['Bat'/1194, l='MpServer', x=10.78, y=41.74, z=181.48], ow['Bat'/364, l='MpServer', x=14.22, y=43.00, z=145.47], qc['Creeper'/1196, l='MpServer', x=4.50, y=44.00, z=180.50], ow['Bat'/1198, l='MpServer', x=29.74, y=28.30, z=157.45], ow['Bat'/1071, l='MpServer', x=13.56, y=52.82, z=139.56], ow['Bat'/815, l='MpServer', x=14.47, y=43.00, z=143.47], qd['Enderman'/1136, l='MpServer', x=30.50, y=19.00, z=136.50], px['item.item.dyePowder.black'/817, l='MpServer', x=-6.59, y=36.29, z=138.13], ow['Bat'/1205, l='MpServer', x=24.50, y=52.02, z=156.50], ow['Bat'/822, l='MpServer', x=20.75, y=42.80, z=151.64], ow['Bat'/1206, l='MpServer', x=10.46, y=41.00, z=179.40], ow['Bat'/823, l='MpServer', x=15.41, y=43.00, z=145.56], qn['Skeleton'/1207, l='MpServer', x=-10.50, y=13.00, z=100.50], qn['Skeleton'/1208, l='MpServer', x=-10.50, y=13.00, z=101.50], ow['Bat'/1017, l='MpServer', x=26.50, y=61.24, z=173.50], ow['Bat'/1146, l='MpServer', x=23.00, y=27.49, z=156.63], ow['Bat'/1083, l='MpServer', x=26.50, y=62.13, z=172.59], ph['Squid'/1149, l='MpServer', x=13.78, y=47.80, z=173.75], qr['Zombie'/1085, l='MpServer', x=33.53, y=18.00, z=139.75], ph['Squid'/959, l='MpServer', x=12.38, y=45.67, z=171.13]]
	Retry entities: 0 total; []
Stacktrace:
	at ayp.a(SourceFile:281)
	at net.minecraft.client.Minecraft.b(SourceFile:1871)
	at net.minecraft.client.Minecraft.run(SourceFile:543)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.4.7
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 49050784 bytes (46 MB) / 134217728 bytes (128 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 17083 (956648 bytes; 0 MB) allocated, 5 (280 bytes; 0 MB) used
	Suspicious classes: No suspicious classes found.
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	LWJGL: 2.9.0
	OpenGL: AMD Radeon RX 570 OpenGL Engine GL version 2.1 ATI-4.6.20, ATI Technologies Inc.
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 3548 (198688 bytes; 0 MB) allocated, 42 (2352 bytes; 0 MB) used
```

**Comment by Shevchik** [comment]
Yep, seems that ench lvl tag type has changed. Minecraft usually doesn't care about exact number type, but i guess that's a place where it does.

**Comment by Shevchik** [comment]
Actually, lvl tag type hasn't changed, that is a mistake on PS part, if there were new enchants before legacy filter, but there weren't any after it, it was adding fake enchantment (to make item glow), but used wrong lvl tag type.

**Comment by Seshpenguin** [comment]
Just tested with 1.18 server (build 664), bug seems to be fixed now!
