### ISSUE TITLE
Skins Do not load when joining

### ISSUE THREAD

**Issue by lukasz4444** [ProtocolSupport/ProtocolSupport#1391]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo) - the newest from jenkins (2022.05.28 at 13:21:24 MSK)

* Server version - paper-1.18.2-388.jar (sorry for that version but chat reporting is pretty bad thing that is why i am using older version)

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

Hi i am using offline mode server to combat chat reporting and little older version to do the same thing.
I play on that server with me and my friends. 
After removing via backwards and rewind leaving only via version for newer versions support 
i saw that skins **doesn't load on joining server**.
They do load after /skin  set <skin> but reset to default after rejoin.

**Comment by lukasz4444** [comment]
**Also i get this issue when logging in**

[14:42:22] [Server thread/WARN]: [ProtocolLib] [Debug] Exception registering converter
java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 0], params=[{Type: class name of net\.minecraft\.(\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*\.)+\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*, Index: null}, {Type: Exact class java.lang.String, Index: 0}, {Type: Exact class java.lang.String, Index: 1}, {Type: Exact class java.lang.String, Index: 4}], paramCount=5}
	at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getWorldTypeClass(MinecraftReflection.java:1191) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.addConverter(BukkitConverters.java:1197) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1176) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1217) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:63) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:46) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:30) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:920) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.access$200(PacketFilterManager.java:71) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerLogin(PacketFilterManager.java:893) ~[ProtocolLib.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:133) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$0(AbstractLoginListenerPlay.java:84) ~[ProtocolSupport.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1545) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:42:23] [Server thread/INFO]: lukasz4444 joined the game

**Comment by lukasz4444** [comment]
[latest.log](https://github.com/ProtocolSupport/ProtocolSupport/files/11121891/latest.log)

**Comment by lukasz4444** [comment]
It was skinrestorer issue so nevermind.
Replacing skinrestorer with https://www.spigotmc.org/resources/skins-1-12-x-1-13-2-1-14-x-1-15-x-1-16-x.70829/ fixed error.
