### ISSUE TITLE
Problem 1.20

### ISSUE THREAD

**Issue by Link0Darck** [ProtocolSupport/ProtocolSupport#1392]
Hello, I have a problem with your plugin to use Fastlogin on my server 1.20.1

```
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ????????????????????????????????????????????????????????????????????[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?                               ERROR
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   Unsupported platform or version 3843-Spigot-b41c46d-4be756e (MC: 1.20.1)
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   This version of plugin only supports
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   server minecraft version 1.18.1
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   and following platforms:
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   - Spigot (https://www.spigotmc.org/)
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?   - Paper (https://papermc.io/)
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ?       https://github.com/ProtocolSupport/ProtocolSupport/
[18:11:45] [Server thread/ERROR]: [ProtocolSupport] ????????????????????????????????????????????????????????????????????[18:11:45] [Server thread/ERROR]: [ProtocolSupport] Platform init failed
java.lang.UnsupportedOperationException: No supported platform detected
        at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:19) ~[?:?]
        at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:64) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:438) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: java.lang.UnsupportedOperationException: Failed to init spigot platform
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:26) ~[?:?]
                at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:64) ~[?:?]
                at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:438) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
                at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
                at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
                at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3843-Spigot-b41c46d-4be756e]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/inventory/CraftItemStack
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:23) ~[?:?]
                ... 6 more
        Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
                at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
                at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
                at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:23) ~[?:?]
                ... 6 more

[18:11:47] [Server thread/ERROR]: [FastLogin] Plugin FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432 has failed to register events for class com.github.games647.fastlogin.bukkit.listener.protocolsupport.ProtocolSupportListener because protocolsupport/api/events/PlayerPropertiesResolveEvent does not exist.
 ```

**Comment by Link0Darck** [comment]
I dropped out due to EULAs
