### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AshourAziz** [ProtocolSupport/ProtocolSupport#147]
[20:20:32] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v4.23.dev
[20:20:32] [Server thread/INFO]: [ProtocolSupport] Allocator: PooledByteBufAllocator(directByDefault: true), direct: true
[20:20:32] [Server thread/INFO]: [ProtocolSupport] Compression level: 3
[20:20:32] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/PacketHandshakingInSetProtocol
[20:20:32] [Server thread/WARN]: 	at protocolsupport.protocol.ServerBoundPacket.<clinit>(ServerBoundPacket.java:49)
[20:20:32] [Server thread/WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:25)
[20:20:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[20:20:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[20:20:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:20:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:20:32] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.PacketHandshakingInSetProtocol
[20:20:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[20:20:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:20:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:20:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:20:32] [Server thread/WARN]: 	... 6 more

**Comment by BeYkeRYkt** [comment]
Build 4.23.dev only for Spigot 1.9! NOT 1.8 !
