### ISSUE TITLE
Can't Craft on MCPE

### ISSUE THREAD

**Issue by Xuwznln** [ProtocolSupport/ProtocolSupport#165]
The latest spigot with protocolsupportPE. MCPE 0.14.2 join but cant craft things.
The latest Protocollib showed:
[15:43:26] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject player.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:859)
  	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:344)
  	at com.comphenix.protocol.injector.PacketFilterManager.onPlayerJoin(PacketFilterManager.java:1041)
  	at com.comphenix.protocol.injector.PacketFilterManager.access$700(PacketFilterManager.java:93)
  	at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerJoin(PacketFilterManager.java:1008)
  	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
  	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
  	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
  	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
  	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
  	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:348)
  	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:174)
  	at protocolsupport.protocol.transformer.mcpe.handler.PELoginListener$1$2.run(PELoginListener.java:138)
  	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:826)
  	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
  	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721)
  	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620)
  	at java.lang.Thread.run(Thread.java:745)
  Dump:
  Parameters: 
    org.bukkit.event.player.PlayerJoinEvent@39a72c12[
      joinMessage=§eXu_wznln joined the game
      player=CraftPlayer{name=Xu_wznln}
      name=PlayerJoinEvent
      async=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3f6c16c1[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@35df3c27
        packetListeners=[PacketAdapter[plugin=ProtocolSupportBarAPI, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutBoss[12, legacy: 255]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@520f2153
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1b858f37
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@23fbfda2
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@460297e1
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6d2c33cb
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@41bb5569
        reporter=com.comphenix.protocol.ProtocolLib$1@5a67e56e
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-647,minecraftVersion=1.9.2}
        library=ProtocolLib v4.0.0-SNAPSHOT-b275
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@746233d2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3684afb2
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@29e04698
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.9.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@1d3174f8
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.PacketFilterManager@3f6c16c1[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@35df3c27
      packetListeners=[PacketAdapter[plugin=ProtocolSupportBarAPI, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutBoss[12, legacy: 255]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@520f2153
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1b858f37
      interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@23fbfda2
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@460297e1
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6d2c33cb
      hasClosed=false
      classLoader=org.bukkit.plugin.java.PluginClassLoader@41bb5569
      reporter=com.comphenix.protocol.ProtocolLib$1@5a67e56e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-647,minecraftVersion=1.9.2}
      library=ProtocolLib v4.0.0-SNAPSHOT-b275
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@746233d2
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=1
      packetCreation=false
      spigotInjector=<null>
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3684afb2
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@29e04698
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.9.2)
      loginPackets=com.comphenix.protocol.injector.LoginPackets@1d3174f8
      debug=false
    ]
  Version:
    ProtocolLib v4.0.0-SNAPSHOT-b275
  Java Version:
    1.8.0_77
  Server:
    git-Paper-647 (MC: 1.9.2)

**Comment by Shevchik** [comment]
This error log has nothing to do with that. Crafting is just not implemented yet.

**Comment by Shevchik** [comment]
Closing this issue because mcpe branch will be rewritten from scratch.
