### ISSUE TITLE
1.9.4

### ISSUE THREAD

**Issue by AshourAziz** [ProtocolSupport/ProtocolSupport#166]
Plugin shutsdown server when booting on a 1.9.4 server no errors

http://pastebin.com/mGwE6TcS

**Comment by Shevchik** [comment]
IT doesn't support 1.9.4 yet.

**Comment by troyfrew** [comment]
I gave it a try.. however my packet fu is not strong enough. The sign update packet appears to have changed which is the biggest issue i'm having in updating it.

**Comment by FunnyCraft** [comment]
updated to 1.9.4

**Comment by AshourAziz** [comment]
1.9.3, 1.9.2 cannot connect to a 1.9.4 server running the latest protocolsupport. 

There is no errors.

**Comment by Shevchik** [comment]
Not supposed to, 1.9.0-1.9.2 support will be added later.

**Comment by AshourAziz** [comment]
So running latest protocolsupport will allow connections for 1.9.3, 1.8.x & 1.9.4 on a 1.9.4 server?

**Comment by Shevchik** [comment]
Yep, only 1.9.4 among all 1.9 versions is supported right now.

**Comment by AshourAziz** [comment]
Do you know when you will have the chance to add such support?

**Comment by troyfrew** [comment]
I just tested commit 1aeefb4bcc7390e6892422fc8b58f1d4b8f16f93 with the latest 1.9.4 spigot from BuildTools

1.4 can't connect (says outdated client)
1.5 can connect
1.6 can connect
1.7 can connect
1.8 can connect
1.9.4 can't ping and can't connect. nothing shows in the server log file at all.

**Comment by TiTo-418** [comment]
Confirmed the @troyfrew's issue

**Comment by hunter688** [comment]
When server in the bungeecord network, cannot connect to server, get timeout. In the console is nothing about connect of client.

**Comment by Shevchik** [comment]
1.9.4 should now work.

**Comment by hunter688** [comment]
with 1.9.4 can connect now, but something wrong whne try connect with 1.9 (server behind bungee) - intead of join to fallback server (which is 1.9.2) get disconnect with: Kicked whilst connecting to lobby:  Unsupported protocol version 107. When remove plugin from lobby server(1.9.4), fallback works as expected.

**Comment by MJRLegends** [comment]
Right i have a 1.9.4 spigot server setup with this plugin and i cant connect with a 1.9.4 client but can using 1.7.10?

**Comment by FunnyCraft** [comment]
When will work on 1.9.2 kernel?

**Comment by AshourAziz** [comment]
When all said and done, is the update going to allow ProtocolSupport to run on let's say a 1.9.2 or 1.9 server and accept 1.8 & 1.9 clients?

**Comment by Shevchik** [comment]
No, it will only allow protocolsupport to run on 1.9.4 and accept 1.4.7-1.9.*

**Comment by hunter688** [comment]
with build 494 can connect with 1.8.9 and 1.9.4. But with 1.9, 1.9.2 show me error in the proxy:

`16:01:21 [SEVERE] [HunterzCZ] <-> ServerConnector [lobby] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 52, widx: 52, cap: 1024))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 52, widx: 52, cap: 1024))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:89)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:79)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 18 more
16:01:21 [INFO] [HunterzCZ] disconnected with: Exception Connecting:DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 52, widx: 52, cap: 1024)) @ io.netty.handler.codec.MessageToMessageDecoder:99
16:01:21 [INFO] [HunterzCZ] <-> ServerConnector [lobby] has disconnected
`

**Comment by ConnorLinfoot** [comment]
I don't believe it's fully ready yet @hunter688. 

I personally get this error when connecting with 1.9.0 (No proxy) http://pastebin.com/HHpyBSN9

**Comment by hunter688** [comment]
I'm only testing and reporting...

**Comment by Shevchik** [comment]
Should be fully working now

**Comment by hunter688** [comment]
Tested join to server with client version 1.8.9, 1.9, 1.9.2, 1.9.4. No problems detected. Good job!
