### ISSUE TITLE
<1.8

### ISSUE THREAD

**Issue by nsoq** [ProtocolSupport/ProtocolSupport#195]
Если заходить с версии, ниже чем 1.8 (Тоесть 1.7, 1.6, 1.5), то игра крашится:
Time: 06.06.16 20:48
Description: Ticking screen

java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tj.a(SourceFile:103)
	at tj.a(SourceFile:389)
	at bdk.a(SourceFile:786)
	at dh.a(SourceFile:45)
	at ci.b(SourceFile:350)
	at bdk.d(SourceFile:95)
	at bdn.c(SourceFile:73)
	at net.minecraft.client.Minecraft.l(SourceFile:1105)
	at net.minecraft.client.Minecraft.K(SourceFile:574)
	at net.minecraft.client.Minecraft.run(SourceFile:526)
	at java.lang.Thread.run(Thread.java:745)

Я думаю, что это из-за какого-то из моих плагинов, но не могу понять, из-за какого именно... Помогите, пожалуйста.

Немного оффтопа: как добавить поддержку MCPE?

**Comment by CreaModZ** [comment]
Please speak in english if you want a response! ;)

**Comment by MrPowerGamerBR** [comment]
@CreaModZ Shevchik is russian, so maybe @nsoq wrote in russian because it is his native language and because Shevchik can understand what he wrote.

**Comment by PurePlugin** [comment]
I'm experiencing the same error, can't use 1.7 clients

**Comment by Shevchik** [comment]
Test now, i did some changes to inventory handling since that time, so maybe it is already fixed.
