### ISSUE TITLE
BUG Reports

### ISSUE THREAD

**Issue by ASuperthings** [ProtocolSupport/ProtocolSupport#215]
It's a good plugin,but I find some bugs in Build-539

[12:00:23 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_91]
at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_91]
at protocolsupport.protocol.storage.ProtocolStorage.setProtocolVersion(ProtocolStorage.java:13) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:156) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:145) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:97) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:27) ~[?:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[12:00:23 INFO]: com.mojang.authlib.GameProfile@61dd91d8[id=19248c99-acee-341e-af56-0d26b3cf5e57,name=15139519899,properties={},legacy=false] (/123.161.213.139:53901) lost connection: Disconnected
[12:00:28 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_91]
at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_91]
at protocolsupport.protocol.storage.ProtocolStorage.setProtocolVersion(ProtocolStorage.java:13) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:156) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:145) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:97) ~[?:?]
at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:27) ~[?:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [PaperSpigot-1.10.2-R0.1.jar:git-Paper-802]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by Shevchik** [comment]
ProtocolSupport doesn't work with native transport.
