### ISSUE TITLE
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

### ISSUE THREAD

**Issue by L4BORG** [ProtocolSupport/ProtocolSupport#220]
```
Error occured at 2016-07-10-23-41
Additional info: /BUNGEE_CORD_IP_ADDRESS:54714, UNKNOWN
Exception class: io.netty.handler.codec.EncoderException
Exception message: java.lang.RuntimeException: An internal error occured.
Exception log:
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_10_R1.NetworkManager$4.run(NetworkManager.java:200)
	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: An internal error occured.
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:485)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.encode(ChannelInjector.java:257)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at protocolsupport.protocol.typeremapper.id.RemappingTable$ArrayBasedIdRemappingTable.getRemap(RemappingTable.java:30)
	at protocolsupport.protocol.legacyremapper.chunk.ChunkTransformer.to19Data(ChunkTransformer.java:49)
	at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_1_9_r2.Chunk.toData(Chunk.java:26)
	at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_1_9_r2.Chunk.toData(Chunk.java:14)
	at protocolsupport.protocol.packet.v_1_9.r2.PacketEncoder.encode(PacketEncoder.java:99)
	at protocolsupport.protocol.pipeline.wrapped.WrappedEncoder.encode(WrappedEncoder.java:25)
	at protocolsupport.protocol.pipeline.wrapped.WrappedEncoder.encode(WrappedEncoder.java:10)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
	... 17 more
```

Latest spigot, PS and protocollib. (dev)

**Comment by L4BORG** [comment]
Latest BungeeCord, latest (dev) PlotSquared,

**Comment by piter909** [comment]
As I see, It is a protocollib error.

**Comment by Shevchik** [comment]
Same as #218
