### ISSUE TITLE
Plugin does not launch on 1.10.2 spigot server for Linux

### ISSUE THREAD

**Issue by slugdude** [ProtocolSupport/ProtocolSupport#227]
I downloaded this, built it, and tried to use it but upon launching the server it says that it "Cannot find main class protocolsupport.ProtocolSupport".

I can include the rest of the exception if you need it.

**Comment by Shevchik** [comment]
Include the rest of the exception log

**Comment by slugdude** [comment]
This is all it gives me in relation to it:

[23:17:57 ERROR]: Could not load 'plugins/ProtocolSupport.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `protocolsupport.ProtocolSupport'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_101]
Caused by: java.lang.ClassNotFoundException: protocolsupport.ProtocolSupport
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_101]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-09f1a19]
	... 7 more

**Comment by Shevchik** [comment]
Redownload the jar, looks like it got corrupted.

**Comment by slugdude** [comment]
Using the latest stable jar, I get this error no matter how many times I re-download it:

[23:33:46 INFO]: [ProtocolSupport] Loading ProtocolSupport v4.24.dev
[23:33:46 INFO]: [ProtocolSupport] Allocator: PooledByteBufAllocator(directByDefault: true), direct: true
[23:33:46 INFO]: [ProtocolSupport] Compression level: 3
[23:33:46 INFO]: [ProtocolSupport] Assume 1.5.2 ping delay: 100
[23:33:46 INFO]: [ProtocolSupport] Assume legacy ping dealy: 200
[23:33:46 INFO]: [ProtocolSupport] Login threads max count: 2147483647, keep alive time: 60
[23:33:46 WARN]: java.lang.NoSuchMethodError: java.lang.reflect.Type.getTypeName()Ljava/lang/String;
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapper.getTypeClassImpl(ValueRemapper.java:17)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapper.<init>(ValueRemapper.java:12)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapperNoOp.<init>(ValueRemapperNoOp.java:34)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapperNoOp.<init>(ValueRemapperNoOp.java:18)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapperNoOp$1.<init>(ValueRemapperNoOp.java:20)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.value.ValueRemapperNoOp.<clinit>(ValueRemapperNoOp.java:20)
[23:33:46 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.SpecificRemapper.<clinit>(SpecificRemapper.java:31)
[23:33:46 WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:38)
[23:33:46 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:302)
[23:33:46 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203)
[23:33:46 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[23:33:46 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[23:33:46 INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.24.dev

Then as soon as the server starts up it stops again.

If I build from source, I get the error from above.

**Comment by Shevchik** [comment]
I guess you need java8 for that.

**Comment by slugdude** [comment]
Thanks, that worked. You should probably note in the readme and such that java 7 and below don't work.
