### ISSUE TITLE
A Error Hapen

### ISSUE THREAD

**Issue by ASuperthings** [ProtocolSupport/ProtocolSupport#231]
Hi!
It's a good plugin.
but a bug sometimes happen,and many players will disconnect.
I don't know the resson.
Version:543
MinecraftVersion:1.10.2
Hope to fix quickly
Thank you very much!
[21:30:21] [Netty Epoll Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_91]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_91]
        at protocolsupport.protocol.storage.ProtocolStorage.setProtocolVersion(ProtocolStorage.java:13) ~[?:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:156) ~[?:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:145) ~[?:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:97) ~[?:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:27) ~[?:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [Spigot-1.10.2-R0.1.jar:git-Spigot-"d9d17b4"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by Shevchik** [comment]
disable epoll (native-transport)
