### ISSUE TITLE
Constant error

### ISSUE THREAD

**Issue by alaaemad15** [ProtocolSupport/ProtocolSupport#268]
I am constantly getting this error:

`[16:42:52] [Netty Epoll Server IO #3/WARN]: java.io.IOException: Error while write(...): Broken pipe
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.Native.writeAddress(Native Method)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel.writeBytes(EpollSocketChannel.java:125)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel.doWriteSingle(EpollSocketChannel.java:337)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:325)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:240)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:676)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1059)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:718)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:42:52] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[16:42:52] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException`

It does it constantly, especially the ClosedChannelException (Spams it over 100 times)

**Comment by Shevchik** [comment]
Disable debug.

**Comment by alaaemad15** [comment]
I can't really use the latest one as I'm using 1.8
