### ISSUE TITLE
1.5.2 & 1.6.4 clients cannot connect.

### ISSUE THREAD

**Issue by Zilacon** [ProtocolSupport/ProtocolSupport#283]
I get "End of Stream" or "Failed to connect" when trying to connect using 1.6.4, 1.5.2 and it wont let me connect at all with 1.4.7 (not really important).

Any idea how to fix this? Heres some screenshots. The top one is a direct link to the vanilla spigot 1.10.2 server and the bottom 2 are bungeecord forced hosts.

![screenshot_9](https://cloud.githubusercontent.com/assets/3002248/19234113/6c02e942-8e9e-11e6-9c3b-79f2c89fa3c1.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/3002248/19234111/6bfe61ec-8e9e-11e6-8280-29a2754c13fa.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/3002248/19234112/6bfef166-8e9e-11e6-9470-09b167c7392f.png)

EDIT: Tested the vanilla server alone (without bungee) and it worked up to 1.5.2 correctly. However with ProtocolSupportBungee i get this:

````
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
	at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:972)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:203)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDataSerializer.readString(PacketDataSerializer.java:12)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.packets.HandshakePacket.read(HandshakePacket.java:31)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readDefinedPacket(PacketReader.java:111)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.reader.PacketReader.readPacket(PacketReader.java:42)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:41)
	at protocolsupport.protocol.transformer.v_1_4_1_5_1_6_core.PacketDecoder.decode(PacketDecoder.java:17)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 22 more
````

I am using the latest version of HexagonBungee

**Comment by Shevchik** [comment]
It's an error on the ProtocolSupportBungee side.
