### ISSUE TITLE
Crash on 1.8

### ISSUE THREAD

**Issue by gabixdev** [ProtocolSupport/ProtocolSupport#308]
#When i run server on 1.8.8 Spigot (Build: git-Spigot-21fe707-e1ebe52) PE version crashes:
```[16:11:31] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v4.23.dev
[16:11:31] [Server thread/INFO]: [ProtocolSupport] Allocator: PooledByteBufAllocator(directByDefault: true), direct: true
[16:11:31] [Server thread/INFO]: [ProtocolSupport] Compression level: 3
[16:11:31] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R2/PacketListener
[16:11:31] [Server thread/WARN]: 	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.<clinit>(InitialPacketDecoder.java:39)
[16:11:31] [Server thread/WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:32)
[16:11:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[16:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[16:11:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[16:11:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:11:31] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R2.PacketListener
[16:11:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:11:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:11:31] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:11:31] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:11:31] [Server thread/WARN]: 	... 6 more```
Edit: Same on 1.10.2

**Comment by Shevchik** [comment]
PE version is dead.
