### ISSUE TITLE
connection throttle problem

### ISSUE THREAD

**Issue by hunter688** [ProtocolSupport/ProtocolSupport#312]
cannot join with 1.11 client to server behind bungee (lobby 1.11). Server log:
<pre>
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to net.minecraft.server.v1_11_R1.HandshakeListener@21ffd166
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to protocolsupport.protocol.pipeline.FakePacketListener@66fac7f4
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Enabled auto read
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to protocolsupport.protocol.packet.handler.common.ModernHandshakeListener@1014f045
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Enabled auto read
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Failed to check connection throttle
java.lang.NoClassDefFoundError: Could not initialize class protocolsupport.protocol.storage.ThrottleTracker
        at protocolsupport.protocol.packet.handler.AbstractHandshakeListener.a(AbstractHandshakeListener.java:50) [ProtocolSupport.jar:?]
        at net.minecraft.server.v1_11_R1.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:29) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at net.minecraft.server.v1_11_R1.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:1) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:126) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at net.minecraft.server.v1_11_R1.NetworkManager.channelRead0(NetworkManager.java:327) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at net.minecraft.server.v1_11_R1.NetworkManager.channelRead0(NetworkManager.java:1) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelRead(LogicHandler.java:40) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:159) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:144) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:96) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26) [ProtocolSupport.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-1.11.jar:git-Spigot-16c940b-ac99d7d]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to protocolsupport.protocol.packet.handler.common.ModernLoginListener@1efbb871
[07:29:04] [LoginProcessingThread/INFO]: UUID of player HunterzCZ is fb2fe292-eec8-4daa-b7b3-d1ff848111d0
[07:29:04] [LoginProcessingThread/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to protocolsupport.protocol.packet.handler.LoginListenerPlay@7c2c000
[07:29:04] [LoginProcessingThread/DEBUG]: Disabled auto read
[07:29:04] [Netty Epoll Server IO #2/DEBUG]: Enabled auto read
[07:29:04] [Server thread/DEBUG]: Set listener of net.minecraft.server.v1_11_R1.NetworkManager@64fd439d to net.minecraft.server.v1_11_R1.PlayerConnection@3414ee34

</pre>

spigot git-Spigot-16c940b-ac99d7d (MC: 1.11)
Protocol Support build 624

**Comment by Shevchik** [comment]
There should have been another exception when this thing occured first time. Try to find it, it will explain what happened.

**Comment by hunter688** [comment]
I think problem is:
<pre>
java.lang.NoClassDefFoundError: Could not initialize class protocolsupport.protocol.storage.ThrottleTracker
        at protocolsupport.protocol.packet.handler.AbstractHandshakeListener.a(AbstractHandshakeListener.java:50)
</pre>
http://pastebin.com/xMpxn4X8

**Comment by hunter688** [comment]
in the bukkit.yml have connection-throttle: 4000, when set to -1 (disabling throttling) not work too.

**Comment by hunter688** [comment]
complete server log:

http://pastebin.com/QsyA1rBR

**Comment by Shevchik** [comment]
Try now.

**Comment by hunter688** [comment]
No error in the server now, but still cannot connect.

I see this error in the bungee log:
<pre>
12:19:07 [SEVERE] [/62.182.234.189:47260|HunterzCZ] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.NullPointerException
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:462)
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:75)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)

</pre>

Its Bungee problem?
![diconnect](https://cloud.githubusercontent.com/assets/1410134/20462378/af425208-af1c-11e6-9090-11fa3a7a6845.png)

**Comment by Shevchik** [comment]
No idea, check if connecting without bungee works.

**Comment by hunter688** [comment]
Without bungee it works. Thanks a lot. I will try locate bungee problem.

**Comment by hunter688** [comment]
FIY:  problem in the picture was due old TitleManager plugin.
