### ISSUE TITLE
1.8.8 client crashes if collecting a netherwart block item (remapped as crops)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#322]
Since this update: https://github.com/ProtocolSupport/ProtocolSupport/commit/609230023792401d0442a54585beac04ad41e470 1.8.8 clients crash if they collect some nether wart block item someone else gives to them. it is now remapped as crops (id 59) that does not exist as an item.

i think it should better be remapped to some full solid block (something like cobblestone as before), because the nether wart block is also solid block (its not the nether wart, but the new nether wart block)

Client crash log:

```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at zx.a(SourceFile:402)
	at wm.k(SourceFile:260)
	at wn.m(SourceFile:490)
	at bew.m(SourceFile:632)
	at pr.t_(SourceFile:1300)
	at wn.t_(SourceFile:277)
	at bew.t_(SourceFile:105)
	at adm.a(SourceFile:1408)
	at adm.g(SourceFile:1386)
	at adm.i(SourceFile:1279)
	at ave.s(SourceFile:1850)
	at ave.av(SourceFile:889)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at magic.launcher.Launcher.main(SourceFile:214)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at zx.a(SourceFile:402)
	at wm.k(SourceFile:260)
	at wn.m(SourceFile:490)
	at bew.m(SourceFile:632)
	at pr.t_(SourceFile:1300)
	at wn.t_(SourceFile:277)
	at bew.t_(SourceFile:105)
	at adm.a(SourceFile:1408)
	at adm.g(SourceFile:1386)

-- Entity being ticked --
Details:
	Entity Type: null (bew)
	Entity ID: 504
	Entity Name: Brokkonaut
	Entity's Exact location: 128,33, 68,00, 43,51
	Entity's Block location: 128,00,68,00,43,00 - World: (128,68,43), Chunk: (at 0,4,11 in 8,2; contains blocks 128,0,32 to 143,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0,03, -0,08, 0,06
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at adm.i(SourceFile:1279)
```

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Brokkonaut** [comment]
Thank you for the fast fixes 👍
