### ISSUE TITLE
NullPointerException: The validated object is null

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#323]
ProtocolSupport dev 637
PaperSpigot dev 933 (MC 1.11)
BlockVersion (Whitelisted 1.10 & 1.11 Clients Only)
ProtocolLib dev 333

```
[07:06:31] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: The validated object is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-933]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[patched_1.11.jar:git-Paper-933]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.NonNullList.set(SourceFile:45) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:141) ~[patched_1.11.jar:git-Paper-933]
	at protocolsupport.server.container.ContainerEnchantTable.a(ContainerEnchantTable.java:166) ~[?:?]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1982) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PacketPlayInEnchantItem.a(SourceFile:22) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PacketPlayInEnchantItem.a(SourceFile:8) ~[patched_1.11.jar:git-Paper-933]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.11.jar:git-Paper-933]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[patched_1.11.jar:git-Paper-933]
	... 5 more
```

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by mibby** [comment]
Thanks. I'll update in a bit and check if it still occurs.

Do you happen to know if this spam is caused by ProtocolSupport or would be an issue in Spigot/Bukkit?

```
	Line 4822: [10:11:12] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:red_shulker_box
	Line 4823: [10:11:12] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:purple_shulker_box
	Line 4824: [10:11:12] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:purple_shulker_box
	Line 4825: [10:11:12] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:light_blue_shulker_box
	Line 4831: [10:11:16] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:white_shulker_box
	Line 4850: [10:12:21] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:green_shulker_box
	Line 4851: [10:12:26] [Server thread/WARN]: Unable to resolve BlockEntity for ItemInstance: minecraft:blue_shulker_box
```

**Comment by Shevchik** [comment]
Spigot issues
