### ISSUE TITLE
Игроки не могут подключиться

### ISSUE THREAD

**Issue by FlamestoN** [ProtocolSupport/ProtocolSupport#324]
Привет.
Установил последнее ядро 1.11, последний dev билд protocollib, и последний билд protocolsupport, при входе на сервер сразу кикает, в файле появляется ошибка:
1.11:
```
Error occured at 2016-11-26-09-56
Additional info: /95.139.220.188:37267, MINECRAFT_1_11
Exception class: io.netty.handler.codec.EncoderException
Exception message: java.lang.ArrayIndexOutOfBoundsException
Exception log:
io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException
	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:47)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at skinsrestorer.bukkit.packet.PacketListener.write(PacketListener.java:85)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException

```
1.8:
```
Error occured at 2016-11-26-09-56
Additional info: /93.80.18.168:57508, MINECRAFT_1_8
Exception class: io.netty.handler.codec.EncoderException
Exception message: java.lang.ArrayIndexOutOfBoundsException
Exception log:
io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException
	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:47)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at skinsrestorer.bukkit.packet.PacketListener.write(PacketListener.java:85)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Shevchik** [comment]
That's not a full exception.

**Comment by FlamestoN** [comment]
http://pastebin.com/Hj5zkzXd

**Comment by FlamestoN** [comment]
В более ранних ошибках, после Cused by есть еще информация:
http://pastebin.com/DwVGmJ8h

**Comment by Shevchik** [comment]
Mob type -1 is not a valid mob. No idea how it got there, but you may want to check your other plugins.

**Comment by FlamestoN** [comment]
Это из-за плагина MyPet.
Посмотрев сорцы, он создаваемым ентити ставит верный typeId, почему в ProtocolSupport приходит -1, не могу понять. Причем это происходит только при входе на сервер, если игрок уже на сервере, и MyPet создает ентити, то с сервера не выкидывает.
Пересобрал ProtocolSupport, и стал назначать всем typeId которые = 0, значение 52 (паук), больше с сервера не кикает при заходе, но все ентити созданные плагином MyPet становятся пауками..
Может быть можно это как-то исправить?

**Comment by Shevchik** [comment]
Use protocollib to see what mypet really sends.

**Comment by FlamestoN** [comment]
Посмотрел что шлется в spawn living entity через protocollib, он показывает varint  моба в type при создании ентити mypet'ом
