### ISSUE TITLE
Legacy json chat error

### ISSUE THREAD

**Issue by Dimatert9** [ProtocolSupport/ProtocolSupport#328]
```
[21:22:24] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:47)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at java.lang.Thread.run(Thread.java:745)
[21:22:24] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.legacyremapper.LegacyChatJson.fixComponent(LegacyChatJson.java:32)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.legacyremapper.LegacyChatJson.walkComponent(LegacyChatJson.java:20)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.legacyremapper.LegacyChatJson.convert(LegacyChatJson.java:15)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.Chat.toData(Chat.java:16)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.packet.middleimpl.clientbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.Chat.toData(Chat.java:11)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:47)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:19)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:37)
[21:22:24] [Netty Epoll Server IO #1/WARN]:   ... 27 more
[21:22:24] [Server thread/INFO]: Techhyyy18 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[21:22:24] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[21:22:24] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[21:22:24] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
```

Maybe it from json msg.
```
            final String json = "[\"\",{\"text\":\"Вас услышало ["+(recipients.size()-1)+"] человек\",\"color\":\"gray\",\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"\",\"extra\":[{\"text\":\""+names+"\",\"color\":\"white\",\"bold:\":\"true\"}]}}}]";

            final PacketContainer chat = new PacketContainer(PacketType.Play.Server.CHAT);
            chat.getChatComponents().write(0, WrappedChatComponent.fromJson(json));
            try {
                ProtocolLibrary.getProtocolManager().sendServerPacket(sender, chat);
            } catch (InvocationTargetException e) {}
```

**Comment by Shevchik** [comment]
Which client version was that?

**Comment by Dimatert9** [comment]
Я даже хз с какой версии он был. Просто кто-то скинул эту ошибку в тему с моей сборки.

names. Это имя игроков из списка. 
```
            String names = "null";
            for (Player namePl : recipients) {
                if (namePl.getName().equals(sender.getName())) {
                    continue;
                }
                if (names.startsWith("null")) {
                    names = namePl.getName();
                } else {
                    names += ", " +namePl.getName();
                }
```
Возможно это даже не связно с этим. Потому что в логах я не вижу никакой ошибки от этого плагина, и нету сообщения в логе, которое отправил игрок. Так что, наврятли причина в этом.
Тот кто скинул ошибку не заходил на рубакит с четверга. Так что спросить у него подробностей я не могу.

**Comment by Shevchik** [comment]
Unable to reproduce anyway, message is passed correctly.

**Comment by Dimatert9** [comment]
Будем ждать и надеяться что тот чел зайдет на рб и увидит моё сообщениею

**Comment by Dimatert9** [comment]
```
[13:34:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: enchantSlots
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [server8.jar:git-Spigot-16c940b-0805f60]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoSuchFieldError: enchantSlots
	at protocolsupport.server.container.ContainerEnchantTable.a(ContainerEnchantTable.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:28) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.splitStack(InventorySubcontainer.java:89) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.Slot.a(SourceFile:101) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:284) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1843) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[server8.jar:git-Spigot-16c940b-0805f60]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[server8.jar:git-Spigot-16c940b-0805f60]
	... 5 more
```

**Comment by Shevchik** [comment]
Was fixed two days ago.

**Comment by Dimatert9** [comment]
Хм.. Как насчет того чтобы добавить в plugin.yml автоматическое дописывание номера билда в version? Чтобы легче было понимать, последняя версия или нет.

**Comment by Shevchik** [comment]
This will need additional build server integration configuration. (Currently it just runs Gradle shell), so the answer is no.

**Comment by Shevchik** [comment]
N additional info for 1 month, i guess we will never know what actually happened there.
