### ISSUE TITLE
Server crashes on reload

### ISSUE THREAD

**Issue by TimoCrafter** [ProtocolSupport/ProtocolSupport#332]
Hello,
my server crashes with the newest version on /rl

`Failed to initialize a channel. Closing: [id: 0x1f0b7a10, /127.
0.0.1:49480 => /127.0.0.1:25601]
java.lang.NoClassDefFoundError: Could not initialize class protocolsupport.proto
col.ConnectionImpl
        at protocolsupport.injector.network.ServerConnectionChannel.initChannel(
ServerConnectionChannel.java:30) ~[?:?]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot-1.11.jar:git-Spigot-f950f8e-4d99fed]
`

**Comment by Shevchik** [comment]
You can't reload this plugin.

**Comment by TimoCrafter** [comment]
Why not?
