### ISSUE TITLE
Enchanting impossible!

### ISSUE THREAD

**Issue by helptiger** [ProtocolSupport/ProtocolSupport#334]
tested with build 645
10:27:35 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: enchantSlots
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_92]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:47) [spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NoSuchFieldError: enchantSlots
	at protocolsupport.server.container.ContainerEnchantTable.a(ContainerEnchantTable.java:47) ~[?:?]
	at net.minecraft.server.v1_11_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:26) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.InventorySubcontainer.splitStack(InventorySubcontainer.java:89) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.Slot.a(SourceFile:101) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.Container.a(Container.java:287) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1843) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_92]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) ~[spigot-1.11.jar:git-Spigot-f950f8e-b6ad714]
	... 5 more

**Comment by helptiger** [comment]
help, help!
item doubled when dropped out from table!

**Comment by Shevchik** [comment]
Try latest dev build, i rebuit it with latest spigot version, so it should work now.

**Comment by helptiger** [comment]
thanks for fast response and fix
