### ISSUE TITLE
Player disconnect on entity damage

### ISSUE THREAD

**Issue by utkabobr** [ProtocolSupport/ProtocolSupport#364]
I'm developing my plugin, and i'm using ProtocolLib to catch use_entity event and when I'm trying to do anything with attacked entity(ProtocolSupport loaded) it disconnects me(And any player), but when i'm trying to do the same thing but without ProtocolSupport it works!

**Comment by Shevchik** [comment]
What is the disconnect message?

**Comment by utkabobr** [comment]
Simply "Disconnected"
Console writote that:
[07:28:37 INFO]: YTKAB0BP lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException
[07:28:37 INFO]: YTKAB0BP left the game

**Comment by Shevchik** [comment]
There should be an full error log in ProtocolSupport-errlog.

**Comment by utkabobr** [comment]
Error occured at 2017-01-24-21-17
Additional info: /127.0.0.1:64110, MINECRAFT_1_11_1
Exception class: io.netty.handler.codec.EncoderException
Exception message: java.lang.IndexOutOfBoundsException
Exception log:
io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException
	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:116)
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:48)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:186)
	at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143)
	at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1090)
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:292)
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:298)
	at net.minecraft.server.v1_11_R1.EntityTracker.sendPacketToEntity(EntityTracker.java:235)
	at net.minecraft.server.v1_11_R1.WorldServer.broadcastEntityEffect(WorldServer.java:1168)
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:902)
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:238)
	at ru.utkacraft.beyond2crafters.Events$1.onPacketReceiving(Events.java:48)
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610)
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577)
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323)
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288)
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
	at protocolsupport.utils.netty.WrappingBuffer.readByte(WrappingBuffer.java:389)
	at protocolsupport.protocol.serializer.ProtocolSupportPacketDataSerializer.readVarInt(ProtocolSupportPacketDataSerializer.java:466)
	at protocolsupport.protocol.serializer.ProtocolSupportPacketDataSerializer.readVarInt(ProtocolSupportPacketDataSerializer.java:55)
	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:44)
	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:20)
	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:37)
	... 65 more

**Comment by utkabobr** [comment]
```
Code:
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.GameMode;
import org.bukkit.entity.Chicken;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;

import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.ProtocolManager;
import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.events.PacketContainer;
import com.comphenix.packetwrapper.WrapperPlayClientUseEntity;

public class Events {
	private ProtocolManager protocolManager;
	public Events(Player player1, Player player2) {
		protocolManager = ProtocolLibrary.getProtocolManager();
		protocolManager.addPacketListener(
				  new PacketAdapter(Bukkit.getServer().getPluginManager().getPlugin("UCB2C"), ListenerPriority.NORMAL, 
				          PacketType.Play.Client.USE_ENTITY) {
				    @Override
				    public void onPacketReceiving(PacketEvent event) {
				        // Item packets (id: 0x29)
				        if (event.getPacketType() == 
				                PacketType.Play.Client.USE_ENTITY) {
							if (event.getPlayer() == player2) {
								if (event.getPlayer().getGameMode() == GameMode.SPECTATOR) {
									PacketContainer packet = event.getPacket();
									Player player = event.getPlayer();
									WrapperPlayClientUseEntity wrapper = new WrapperPlayClientUseEntity(packet);
									Entity target = wrapper.getTarget(event);
									player.sendMessage(ChatColor.AQUA + "*pluginname*] " + ChatColor.GOLD + "Debug: " + wrapper.getType().toString() + " " + target.getType());
									if (target instanceof Chicken) { // Testing type chicken(damageable)
										((Chicken) target).setBaby();
										((Chicken) target).damage(1,(Entity) player);
									}
									event.setCancelled(true);
								}
				        	}
				        }
				    }
				});
	}
}
```

**Comment by Shevchik** [comment]
You are accessing Bukkit API async which is the problem.
Fix that first, and if the problem continues post a new exception.

**Comment by utkabobr** [comment]
But how it works without ProtocolSupport?

**Comment by utkabobr** [comment]
And than I can normally damage attacker with the same method with a ProtocolSupport

**Comment by Shevchik** [comment]
It works by pure luck.

**Comment by utkabobr** [comment]
Yes, you're right, with elevating to main thread it works:
```
Bukkit.getScheduler().runTask(Bukkit.getServer().getPluginManager().getPlugin("UCB2C"), new Runnable() {
											@Override
											public void run() {
												((Damageable) target).damage(10,(Entity) player);
											}
										});
```
