### ISSUE TITLE
NameTagEdit error on 1.11 server with 1.7.x

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#382]
You get this error on join with a 1.7.x client and the client gets kicked to the hub.  If you remove NameTagEdit the error goes away

```
[16:18:25] [Server thread/WARN]: java.lang.NullPointerException
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.packets.PacketWrapper.setupDefaults(PacketWrapper.java:51)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.NametagManager.sendTeams(NametagManager.java:132)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.NametagHandler.onPlayerJoin(NametagHandler.java:155)
[16:18:25] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor480.invoke(Unknown Source)
[16:18:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:18:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
[16:18:25] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.LoginListenerPlay.tryJoin(LoginListenerPlay.java:143)
[16:18:25] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.LoginListenerPlay.F_(LoginListenerPlay.java:126)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[16:18:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:18:25] [Server thread/WARN]: java.lang.NullPointerException
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.packets.PacketWrapper.setupMembers(PacketWrapper.java:43)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:19)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.NametagManager.sendTeams(NametagManager.java:132)
[16:18:25] [Server thread/WARN]: 	at com.nametagedit.plugin.NametagHandler.onPlayerJoin(NametagHandler.java:155)
[16:18:25] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor480.invoke(Unknown Source)
[16:18:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:18:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:18:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
[16:18:25] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.LoginListenerPlay.tryJoin(LoginListenerPlay.java:143)
[16:18:25] [Server thread/WARN]: 	at protocolsupport.protocol.packet.handler.LoginListenerPlay.F_(LoginListenerPlay.java:126)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[16:18:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[16:18:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Shevchik** [comment]
No a protocolsupport problem
