### ISSUE TITLE
Glowstone not switching offline mode

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#391]
I am unable to connect to Glowstone in offline mode without verification, I get a failed to verify username kick message and this error log in Glowstone.  ProtocolSupport is the only plugin in the server:
```
2017/02/18 22:02:28 [INFO] Binding server to 0.0.0.0/0.0.0.0:25565...
2017/02/18 22:02:29 [INFO] Successfully bound server to 0.0.0.0/0.0.0.0:25565.
2017/02/18 22:02:29 [INFO] Ready for connections.
2017/02/18 22:11:53 [INFO] Disconnecting GameProfile(id=null,name=squirrelmail) (/172.106.16.90:41245): Failed to verify username!
2017/02/18 22:11:53 [SEVERE] Exception verifying squirrelmail
java.lang.NullPointerException
	at protocolsupport.zplatform.impl.glowstone.network.GlowStoneNetworkManagerWrapper.getSpoofedUUID(GlowStoneNetworkManagerWrapper.java:125)
	at protocolsupport.protocol.packet.handler.AbstractLoginListener.initOfflineModeGameProfile(AbstractLoginListener.java:95)
	at protocolsupport.protocol.packet.handler.PlayerLookupUUID.run(PlayerLookupUUID.java:37)
	at protocolsupport.protocol.packet.handler.AbstractLoginListener$2.run(AbstractLoginListener.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017/02/18 22:11:53 [INFO] [/172.106.16.90:41245] kicked: Failed to verify username!
2017/02/18 22:14:44 [INFO] Disconnecting GameProfile(id=null,name=squirrelmail) (/172.106.16.90:41395): Failed to verify username!
2017/02/18 22:14:44 [SEVERE] Exception verifying squirrelmail
java.lang.NullPointerException
	at protocolsupport.zplatform.impl.glowstone.network.GlowStoneNetworkManagerWrapper.getSpoofedUUID(GlowStoneNetworkManagerWrapper.java:125)
	at protocolsupport.protocol.packet.handler.AbstractLoginListener.initOfflineModeGameProfile(AbstractLoginListener.java:95)
	at protocolsupport.protocol.packet.handler.PlayerLookupUUID.run(PlayerLookupUUID.java:37)
	at protocolsupport.protocol.packet.handler.AbstractLoginListener$2.run(AbstractLoginListener.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017/02/18 22:14:44 [INFO] [/172.106.16.90:41395] kicked: Failed to verify username!
```

With this error its impossible to use Bungee on a glowstone server because the server must be in offline mode.

**Comment by Shevchik** [comment]
Spoofed uuid didn't make it to spoofed parameters for some reason, will check it later.

**Comment by Shevchik** [comment]
Found the problem

**Comment by Shevchik** [comment]
Should be fixed now
