### ISSUE TITLE
PandaWire Compatibility 

### ISSUE THREAD

**Issue by wow4201** [ProtocolSupport/ProtocolSupport#398]
Hey,

Any possibilities to have this made compatible with PandaWire?
PandaWire is pretty much the only solution to having RedStone on a server...

**Comment by Shevchik** [comment]
Launched the server, everything works fine. Post your error.

**Comment by wow4201** [comment]
[20:03:56] [Server thread/INFO]: [PandaWire] Enabling PandaWire v1.0.1-SNAPSHOT
[20:03:56] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader PandaWire v1.0.1-SNAPSHOT
[20:03:56] [Server thread/WARN]: java.lang.IllegalAccessException: Can not set static final net.minecraft.server.v1_10_R1.BlockRedstoneWire field net.minecraft.server.v1_10_R1.Blocks.REDSTONE_WIRE to net.md_5.PandaRedstoneWire
[20:03:56] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source)
[20:03:56] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source)
[20:03:56] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(Unknown Source)
[20:03:56] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Unknown Source)
[20:03:56] [Server thread/WARN]: 	at net.md_5.ReflectUtil.setStatic(ReflectUtil.java:43)
[20:03:56] [Server thread/WARN]: 	at net.md_5.PandaWire.onEnable(PandaWire.java:14)
[20:03:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[20:03:56] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:03:56] [Server thread/WARN]: 	at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:216)
[20:03:56] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:03:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[20:03:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[20:03:56] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:204

**Comment by MrPowerGamerBR** [comment]
@wow4201 are you sure this is a conflict with ProtocolSupport?

**Comment by MrPowerGamerBR** [comment]
@wow4201 also, as far as I know, the latest PandaWire version only works in 1.11.2, so be sure that you aren't using that version.

**Comment by wow4201** [comment]
I have a 1.10.2 server running protocolsupport [ProtocolSupport] Loading ProtocolSupport v4.25.dev
The situation is more complicated then just upgrading to 1.11, I have a perfect lag free, crash free, all plugins working setup on 1.10.2  trying to run PandaWire (1.10.2 version)

**Comment by Shevchik** [comment]
Not latest protocolsupport is not supported.

**Comment by Shevchik** [comment]
If it has the repo available, i can commit the needed changes.
