### ISSUE TITLE
Error in the ProtocolSupport-errlog

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#407]
Hi, I found an error in the errlog file: 
`Additional info: /address, MINECRAFT_1_7_10
Exception class: io.netty.handler.codec.DecoderException
Exception message: java.lang.RuntimeException: Missing type on ListTag
Exception log:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Missing type on ListTag
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Missing type on ListTag
	at net.minecraft.server.v1_11_R1.NBTTagList.load(SourceFile:59)
	at net.minecraft.server.v1_11_R1.NBTTagList.load(SourceFile:66)
	at net.minecraft.server.v1_11_R1.NBTTagList.load(SourceFile:66)
	at net.minecraft.server.v1_11_R1.NBTTagCompound.a(SourceFile:427)
	at net.minecraft.server.v1_11_R1.NBTTagCompound.load(SourceFile:76)
	at net.minecraft.server.v1_11_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)
	at net.minecraft.server.v1_11_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
	at protocolsupport.zplatform.impl.spigot.itemstack.SpigotNBTTagCompoundWrapper.fromStream(SpigotNBTTagCompoundWrapper.java:42)
	at protocolsupport.zplatform.impl.spigot.SpigotWrapperFactory.createNBTCompoundFromStream(SpigotWrapperFactory.java:35)
	at protocolsupport.protocol.serializer.ProtocolSupportPacketDataSerializer.readTag(ProtocolSupportPacketDataSerializer.java:227)
	at protocolsupport.protocol.serializer.ProtocolSupportPacketDataSerializer.readItemStack(ProtocolSupportPacketDataSerializer.java:197)
	at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_1_4__1_5__1_6__1_7.BlockPlace.readFromClientData(BlockPlace.java:12)
	at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:31)
	at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:15)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 14 more`

**Comment by Shevchik** [comment]
Ignore that. Somebody send an invalid nbt data.
