### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#418]
Error occured at 2017-03-12-13-16
Additional info: /118.193.27.4:55157, UNKNOWN
Exception class: io.netty.handler.codec.DecoderException
Exception message: 3 is not a valid packet id
Exception log:
io.netty.handler.codec.DecoderException: 3 is not a valid packet id
	at protocolsupport.protocol.pipeline.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:40)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:166)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:98)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Error occured at 2017-03-12-13-16
Additional info: /118.193.27.4:51235, UNKNOWN
Exception class: io.netty.handler.codec.DecoderException
Exception message: 69 is not a valid packet id
Exception log:
io.netty.handler.codec.DecoderException: 69 is not a valid packet id
	at protocolsupport.protocol.pipeline.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:40)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:166)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:98)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

using build 30.

Maybe caused by PacketPlayOutBoss packet sent to <1.9 players ?

**Comment by Shevchik** [comment]
No, that error are caused by something that is not minecraft sending data to the server.

**Comment by NEZNAMY** [comment]
Some cheater ? O_o

**Comment by Shevchik** [comment]
No, most likely nmap scanning for known protocols.
