### ISSUE TITLE
And another error

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#422]
Error occured at 2017-03-18-07-17
Additional info: /90.178.34.253:54010, MINECRAFT_1_8
Exception class: io.netty.handler.codec.DecoderException
Exception message: protocolsupport.libs.com.google.gson.JsonSyntaxException: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
Exception log:
io.netty.handler.codec.DecoderException: protocolsupport.libs.com.google.gson.JsonSyntaxException: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: protocolsupport.libs.com.google.gson.JsonSyntaxException: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at protocolsupport.libs.com.google.gson.Gson.assertFullConsumption(Gson.java:863)
	at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:853)
	at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:801)
	at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:773)
	at protocolsupport.api.chat.ChatAPI.fromJSON(ChatAPI.java:30)
	at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.CustomPayload.remapBookPages(CustomPayload.java:54)
	at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.CustomPayload.readFromClientData(CustomPayload.java:38)
	at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:32)
	at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:15)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 19 more
Caused by: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at protocolsupport.libs.com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at protocolsupport.libs.com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at protocolsupport.libs.com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at protocolsupport.libs.com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at protocolsupport.libs.com.google.gson.Gson.assertFullConsumption(Gson.java:859)
	... 28 more

Using build 30

**Comment by Shevchik** [comment]
Try reproducing this again with new build (this exception happened when writing/signing book with 1.8)
