### ISSUE TITLE
Lol another error

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#423]
Error occured at 2017-03-11-15-52
Additional info: /178.62.28.94:41138, UNKNOWN
Exception class: java.lang.IndexOutOfBoundsException
Exception message: null
Exception log:
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
	at protocolsupport.protocol.serializer.VarNumberSerializer.readVarInt(VarNumberSerializer.java:13)
	at protocolsupport.protocol.pipeline.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:35)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:166)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:98)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Using build 30

**Comment by Shevchik** [comment]
Something that is not minecraft attempted to connect to server.
