### ISSUE TITLE
PE random error

### ISSUE THREAD

**Issue by DaMatrix** [ProtocolSupport/ProtocolSupport#429]
I've been getting this error every now and then in the log (using pe branch):
`[11:33:36 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: channel not registered to an event loop
        at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:107) ~[spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:128) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:608) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:874) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.AbstractChannel.read(AbstractChannel.java:224) ~[spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at protocolsupport.libs.udpserversocketchannel.channel.NioUdpServerChannel.doReadMessages(NioUdpServerChannel.java:143) ~[?:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:68) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [spigot.jar:git-Spigot-6de2fbc-c1aa859]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`
Not sure if it means anything, just putting this out there. I'm not sure what causes it, it just seems to get printed out in the log now and again even without any players online.

**Comment by 7kasper** [comment]
Did you try connecting with. Windows 10 Even listing the servers in Minecraft: Windows 10 causes this for me.

**Comment by DaMatrix** [comment]
I don't have windows, only linux. I can connect with mcpelauncher-linux fine though.

**Comment by NycuRO** [comment]
@DaMatrix for me server not show started on server.

Can you give me your files of server, please?

**Comment by caspervanneck** [comment]
@NycuRO it's only for offine mode

**Comment by caspervanneck** [comment]
Than it will work

**Comment by Shevchik** [comment]
It's an issue in underlying UdpServerSocketCHannel library which i'm currently trying to fix.

**Comment by DaMatrix** [comment]
great, thanks! @Shevchik 
@NycuRO if you want to use the script i have for running ProtocolSupportPE on production, then check out https://github.com/2pocket2edition/Server2p2e . You can use ./setup.sh to set stuff up, ./update.sh to update everything, and ./start.sh to start. (only works on Linux lul)

**Comment by NycuRO** [comment]
@DaMatrix I don't have grandlew installed on linux

**Comment by DaMatrix** [comment]
You don't need gradle, ProtocolSupport comes with gradlew. And even if it didn't you could just `sudo apt install gradle`
