### ISSUE TITLE
RuntimeException: An internal error occured 

### ISSUE THREAD

**Issue by sionzeecz** [ProtocolSupport/ProtocolSupport#463]
ProtocolSupport [#43 ](https://build.true-games.org/job/ProtocolSupport/43)
PaperSpigot 1.11.2-R0.1-SNAPSHOT (1081)

`Error occured at 2017-04-16-20-03
Additional info: /109.231.146.50:51801, MINECRAFT_1_11_1
Exception class: io.netty.handler.codec.DecoderException
Exception message: java.lang.RuntimeException: An internal error occured.
Exception log:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: An internal error occured.
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:522)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	... 21 more
Caused by: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (32 > 16)
	at net.minecraft.server.v1_11_R1.PacketDataSerializer.e(PacketDataSerializer.java:290)
	at net.minecraft.server.v1_11_R1.PacketLoginInStart.a(SourceFile:23)
	at net.minecraft.server.v1_11_R1.PacketDecoder.decode(SourceFile:40)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
	... 23 more`

**Comment by Shevchik** [comment]
Player connected with username longer than 16 symbols.

**Comment by gdude2002** [comment]
Man, that's amusing. How does that happen?

**Comment by DaMatrix** [comment]
Probably cracked launcher/hack client

**Comment by DaMatrix** [comment]
that's exactly the point, that error says itself that the name IS longer than 16.

**Comment by sionzeecz** [comment]
Okey, then why is it throwed when I connect to the server?
I don't have warez account.

**Comment by Shevchik** [comment]
It's not cme insdie protocolsupport. It's a CME inside the server itself. Not a ProtocolSupport issue.
