### ISSUE TITLE
NPE Exception verifying Bedrok

### ISSUE THREAD

**Issue by sionzeecz** [ProtocolSupport/ProtocolSupport#467]
Server: PaperSpigot 1090
ProtocolSupport: [#46](https://build.true-games.org/job/ProtocolSupport/46/)

`[17:42:52 ERROR]: Exception verifying Bedrok
java.lang.NullPointerException
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.keepConnection(AbstractLoginListenerPlay.java:123) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.finishLogin(AbstractLoginListenerPlay.java:54) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListener.setReadyToAccept(AbstractLoginListener.java:222) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.PlayerLookupUUID.fireLoginEvents(PlayerLookupUUID.java:98) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.PlayerLookupUUID.run(PlayerLookupUUID.java:38) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListener$2.run(AbstractLoginListener.java:145) [ProtocolSupport.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by gdude2002** [comment]
Can't 100% confirm it, but that doesn't look like a ProtocolSupport problem.

Lines in question:
```
	protected void keepConnection() {
		// custom payload does nothing on a client when sent with invalid tag,
		// but it resets client readtimeouthandler, and that is exactly what we need
		networkManager.sendPacket(ServerPlatform.get().getPacketFactory().createEmptyCustomPayloadPacket("PS|KeepAlive"));
		// we also need to reset server readtimeouthandler
		ChannelHandlers.getTimeoutHandler(networkManager.getChannel().pipeline()).setLastRead();  // <-- NPE here
	}
```

**Comment by Shevchik** [comment]
Sometimes player disconnects before logging in and netty tears down the pipeline before login task reaches this line which causes NPE.

**Comment by Shevchik** [comment]
Should no longer be happening.
