### ISSUE TITLE
Kick 1.8.8 when editing book

### ISSUE THREAD

**Issue by goblin9700** [ProtocolSupport/ProtocolSupport#472]
Вылетает клиент при нажатии на кнопку "Готово" при редактировании книги. Версия клиента 1.8.8. 
Сервер версии git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

`[19:40:38] [Netty Server IO #1/WARN]: io.netty.handler.codec.DecoderException: protocolsupport.api.chat.ChatAPI$JsonParseException: Unable to parse json string мы ее похитили есле она тебе дорога ищи ее замен 1000 изумрудов
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[19:40:38] [Netty Server IO #1/WARN]:   at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[19:40:38] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

`

**Comment by Shevchik** [comment]
Check protocolsupport-errlog it should contain more.

**Comment by goblin9700** [comment]
Error occured at 2017-05-06-19-55
Additional info: 

> /*:45288,

 MINECRAFT_1_8
Exception class: io.netty.handler.codec.DecoderException
Exception message: protocolsupport.api.chat.ChatAPI$JsonParseException: Unable to parse json string мы ее похитили есле она тебе дорога ищи ее замен 1000 изумрудов
Exception log:
io.netty.handler.codec.DecoderException: protocolsupport.api.chat.ChatAPI$JsonParseException: Unable to parse json string мы ее похитили есле она тебе дорога ищи ее замен 1000 изумрудов
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
Caused by: protocolsupport.api.chat.ChatAPI$JsonParseException: Unable to parse json string мы ее похитили есле она тебе дорога ищи ее замен 1000 изумрудов
        at protocolsupport.api.chat.ChatAPI.fromJSON(ChatAPI.java:38)
        at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.CustomPayload.remapBookPages(CustomPayload.java:54)
        at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_1_8__1_9_r1__1_9_r2__1_10__1_11.CustomPayload.readFromClientData(CustomPayload.java:38)
        at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:32)
        at protocolsupport.protocol.pipeline.version.AbstractModernWithReorderPacketDecoder.decode(AbstractModernWithReorderPacketDecoder.java:15)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        ... 19 more
Caused by: protocolsupport.libs.com.google.gson.JsonSyntaxException: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at protocolsupport.libs.com.google.gson.Gson.assertFullConsumption(Gson.java:863)
        at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:853)
        at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:801)
        at protocolsupport.libs.com.google.gson.Gson.fromJson(Gson.java:773)
        at protocolsupport.api.chat.ChatAPI.fromJSON(ChatAPI.java:35)
        ... 24 more
Caused by: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at protocolsupport.libs.com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
        at protocolsupport.libs.com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
        at protocolsupport.libs.com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at protocolsupport.libs.com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at protocolsupport.libs.com.google.gson.Gson.assertFullConsumption(Gson.java:859)
        ... 28 more

**Comment by Shevchik** [comment]
Should be fixed now
