### ISSUE TITLE
Lots of java.lang.IndexOutOfBoundsException in ProtocolSupport-errorlog

### ISSUE THREAD

**Issue by Pocke01** [ProtocolSupport/ProtocolSupport#487]
ProtocolSupport version: 
[ProtocolSupport] Loading ProtocolSupport v4.26.dev

Spigot version:
This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

These errors are being generated as soon as the server is started. Lots of them. 

`Error occured at 2017-05-30-09-24
Additional info: /192.168.x.x:56462, UNKNOWN
Exception class: java.lang.IndexOutOfBoundsException
Exception message: null
Exception log:
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
	at protocolsupport.protocol.serializer.VarNumberSerializer.readVarInt(VarNumberSerializer.java:13)
	at protocolsupport.protocol.pipeline.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:35)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:166)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:98)
	at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Shevchik** [comment]
Not an error. Some sort of software ping server with invalid data.
