### ISSUE TITLE
Problem when pinging Server over Socket

### ISSUE THREAD

**Issue by Bentipa** [ProtocolSupport/ProtocolSupport#491]
Heyho,
me as the developer of multiple sign system have the problem that ProtocolSupport blocks incoming ServerPings while server without ProtocolSupport simply respond to them.

They answer with an EOFException:
`java.io.EOFException
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at java.io.DataInputStream.readByte(Unknown Source)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at me.Bentipa.BungeeSigns.pinghelp.ServerPing.readVarInt(ServerPing.java:59)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at me.Bentipa.BungeeSigns.pinghelp.ServerPing.fetchData(ServerPing.java:131)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at me.Bentipa.BungeeSigns.sheduler.BungeeSignsPinger$2.run(BungeeSignsPinger.java:132)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:14:27] [Craft Scheduler Thread - 5/WARN]:   at java.lang.Thread.run(Unknown Source)`

On the target server sometimes this happens:
`Additional info: /192.168.x.x:44222, UNKNOWN
Exception class: java.lang.IndexOutOfBoundsException
Exception message: null
Exception log:
java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
    at protocolsupport.protocol.serializer.VarNumberSerializer.readVarInt(VarNumberSerializer.java:13)
    at protocolsupport.protocol.pipeline.initial.ProtocolUtils.readNettyHandshake(ProtocolUtils.java:35)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.attemptDecodeNettyHandshake(InitialPacketDecoder.java:166)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.decode(InitialPacketDecoder.java:140)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:98)
    at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelRead0(InitialPacketDecoder.java:26)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:748)`
(not related to the EOFException I guess)

Both traces are from customers so I can not confirm 100 percent that they are correct.
Is there a possibilty to make the plugins compatible?
If you want to I can also send you the code for pinging but I would want to do that privately.

Thanks,
Benny

**Comment by gdude2002** [comment]
You should double-check your implementation, honestly it seems like you may just not be crafting the packets correctly.

Maybe @Shevchik will be able to tell you more on that.

**Comment by Bentipa** [comment]
Yeah @gdude2002, maybe @Shevchik can get in contact with me.

**Comment by Shevchik** [comment]
Show the code that you use to ping the server.

**Comment by gdude2002** [comment]
It's been five days - any update, @Bentipa?

**Comment by Bentipa** [comment]
@Shevchik 
Sorry I did not receive any notification ^^
https://hastebin.com/owakorobaq.java this should be the code you need I guess, thanks for your help 👍 

@gdude2002 
Sorry to you too ^^

**Comment by Shevchik** [comment]
That source code doesn't contain a valid packet format

**Comment by Bentipa** [comment]
@Shevchik yep that is, I guess, because I don't know a lot about packets in minecraft...
can you help me out somehow ? Some refs where I could read more about it ? Thanks a lot for your time

**Comment by Shevchik** [comment]
wiki.vg contains all info about packets.

**Comment by Bentipa** [comment]
And what do you mean by it does not contain a valid packet format ? How are you supposed to implement these packets ? In the source code it tries to handshake and sens the SLP Packet 0x00

**Comment by Shevchik** [comment]
1. The packet length is varint, not int
2. String length is based on byte array length returned by String::getBytes(Charset)

**Comment by Bentipa** [comment]
Sorry I can not follow you, could you mention the corresponding lines?

**Comment by MrPowerGamerBR** [comment]
@Bentipa 

Change the packet length from int to VarInt @ line 121

The second one is (I assume) @ line 116

**Comment by Bentipa** [comment]
@MrPowerGamerBR thank your for your assistence, I changed to https://hastebin.com/arapudakel.css hope this now more likely correct
