### ISSUE TITLE
Protocol support disconnect

### ISSUE THREAD

**Issue by MastoryMd5** [ProtocolSupport/ProtocolSupport#493]
Hi when i try to join in my server 1.11.2 i can't connect because of this error. 
https://hastebin.com/bukedicowo.sql this is the only error in my logs

**Comment by gdude2002** [comment]
Are you using the latest version of ProtocolSupport from Jenkins? When did you build your copy of Spigot? Are you using Bungee or something similar? Are you running in offline mode?

---

Here's the log provided in the link above, since Hastebin is pretty quick to delete stuff.

```
[05:46:56 INFO]: Done (4.918s)! For help, type "help" or "?"
[05:46:56 INFO]: [Vault] Checking for Updates ...
[05:46:56 INFO]: [Vault] No new version available
[05:48:39 INFO]: /5.152.142.61:33059 lost connection: Disconnected
[05:48:51 INFO]: GameProfile(id=fe36e52b-2e41-3568-a04d-8348de98de35,name=Mastory_Md5) (/5.152.142.61:48467) lost connection: Disconnected
[05:48:52 INFO]: UUID of player Mastory_Md5 is fe36e52b-2e41-3568-a04d-8348de98de35
[05:48:52 INFO]: Disconnecting GameProfile(id=fe36e52b-2e41-3568-a04d-8348de98de35,name=Mastory_Md5) (/5.152.142.61:48467): Failed to verify username!
[05:48:52 ERROR]: Exception verifying Mastory_Md5
java.lang.NullPointerException
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.keepConnection(AbstractLoginListenerPlay.java:123) ~[ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.finishLogin(AbstractLoginListenerPlay.java:54) ~[ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener.setReadyToAccept(AbstractLoginListener.java:221) ~[ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.PlayerLookupUUID.fireLoginEvents(PlayerLookupUUID.java:98) ~[ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.PlayerLookupUUID.run(PlayerLookupUUID.java:38) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener$2.run(AbstractLoginListener.java:144) [ProtocolSupport.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
>
```

**Comment by MastoryMd5** [comment]
Protocol support Version 4.25 Spigot is the latest 1.11.2 i'm using waterfall offline modei tried to set use-native-transport in server.properties to false but nothing :c

**Comment by gdude2002** [comment]
If you're using waterfall, have you set your server to offline mode as well?

**Comment by MastoryMd5** [comment]
Yes

**Comment by gdude2002** [comment]
I think we'll need to wait for @Shevchik on this one - he's pretty busy but he should be around later on today

**Comment by MastoryMd5** [comment]
Ok no problem

**Comment by Shevchik** [comment]
That's not the latest version. Update to latest dev build and post new log.
