### ISSUE TITLE
1.11.2/1.12 clients on 1.12 server, regulary crashes

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#495]
The client crashes sometimes when using 1.11.2 clients on 1.12 servers - This is the clients exception:

[23:42:28] [Client thread/FATAL]: Reported exception thrown!
f: Ticking entity
	at ajs.k(SourceFile:1385) ~[ajs.class:?]
	at bes.t(SourceFile:1652) ~[bes.class:?]
	at bes.av(SourceFile:970) ~[bes.class:?]
	at bes.a(SourceFile:398) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at magic.launcher.Launcher.main(SourceFile:214) [MagicLauncher.exe:?]
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at sk.l(SourceFile:81) ~[sk.class:?]
	at sk.l_(SourceFile:173) ~[sk.class:?]
	at sx.canSkipUpdate(EntityLiving.java:1633) ~[sx.class:?]
	at sx.A_(EntityLiving.java:377) ~[sx.class:?]
	at xk.A_(SourceFile:225) ~[xk.class:?]
	at ajs.a(SourceFile:1517) ~[ajs.class:?]
	at ajs.h(SourceFile:1495) ~[ajs.class:?]
	at ajs.k(SourceFile:1378) ~[ajs.class:?]
	... 15 more

**Comment by Brokkonaut** [comment]
This also happens with 1.12 clients on 1.12 server (but only when protocolsupport is installed)

Exception on 1.12 client:
[00:08:04] [Client thread/FATAL]: Reported exception thrown!
f: Ticking entity
	at ams.k(SourceFile:1389) ~[1.12.jar:?]
	at bhz.t(SourceFile:1691) ~[1.12.jar:?]
	at bhz.az(SourceFile:1000) ~[1.12.jar:?]
	at bhz.a(SourceFile:419) [1.12.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at magic.launcher.Launcher.main(SourceFile:214) [MagicLauncher.exe:?]
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at vb.l(SourceFile:81) ~[1.12.jar:?]
	at zt.n(SourceFile:45) ~[1.12.jar:?]
	at aak.n(SourceFile:210) ~[1.12.jar:?]
	at vn.B_(SourceFile:1742) ~[1.12.jar:?]
	at vo.B_(SourceFile:281) ~[1.12.jar:?]
	at aak.B_(SourceFile:225) ~[1.12.jar:?]
	at ams.a(SourceFile:1523) ~[1.12.jar:?]
	at ams.h(SourceFile:1499) ~[1.12.jar:?]
	at ams.k(SourceFile:1382) ~[1.12.jar:?]
	... 9 more

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Brokkonaut** [comment]
thank you :)
