### ISSUE TITLE
server auto restarts after getting this error:

### ISSUE THREAD

**Issue by Legoman99573** [ProtocolSupport/ProtocolSupport#507]
```
15.06 10:00:15 [Server] ERROR [ProtocolSupport] Error when loading, make sure you are using supported server version
15.06 10:00:15 [Server] INFO java.lang.IllegalStateException: MCPE doesn't support online-mode
15.06 10:00:15 [Server] INFO at protocolsupport.zplatform.pe.MCPEServer.<init>(MCPEServer.java:42) ~[ProtocolSupport.jar:?]
15.06 10:00:15 [Server] INFO at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:76) [ProtocolSupport.jar:?]
15.06 10:00:15 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [spigot-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
15.06 10:00:15 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
15.06 10:00:15 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-cd6ba67-f7d14f1]
15.06 10:00:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

IDK if its a PE bug or if i am missing something. Affects PE version.

**Comment by Shevchik** [comment]
Read the exception cause

**Comment by Legoman99573** [comment]
Even when xbox live support was added? Im confused a little.

**Comment by Shevchik** [comment]
It only adds ability to login with xbox live token, not online mode support
