### ISSUE TITLE
1.12 Not Supported but in Info 1.12 marked!

### ISSUE THREAD

**Issue by Shoxxo** [ProtocolSupport/ProtocolSupport#556]
```quote
[11:09:55] [Server thread/INFO]: Starting minecraft server version 1.12
[11:09:55] [Server thread/INFO]: Loading properties
[11:09:55] [Server thread/INFO]: Default game type: SURVIVAL
[11:09:55] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[11:09:55] [Server thread/INFO]: Debug logging is disabled
[11:09:55] [Server thread/INFO]: Server Ping Player Sample Count: 12
[11:09:55] [Server thread/INFO]: Using 4 threads for Netty based IO
[11:09:55] [Server thread/INFO]: Generating keypair
[11:09:55] [Server thread/INFO]: Starting Minecraft server on *:25566
[11:09:55] [Server thread/INFO]: Using default channel type
[11:09:55] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[11:09:55] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v4.25
[11:09:55] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/NetworkManager
[11:09:55] [Server thread/WARN]: 	at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:25)
[11:09:55] [Server thread/WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:34)
[11:09:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307)
[11:09:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
[11:09:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[11:09:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:09:55] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.NetworkManager
[11:09:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[11:09:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[11:09:55] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:09:55] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:09:55] [Server thread/WARN]: 	... 6 more
[11:09:55] [Server thread/ERROR]: [ProtocolSupport] Unsupported server implementation type, shutting down
[11:09:55] [Server thread/INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.25
[11:09:55] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:09:55] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:09:55] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[11:09:55] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[11:09:55] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:09:55] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[11:09:55] [Server thread/INFO]: Preparing level "lobby"
[11:09:55] [Server thread/INFO]: -------- World Settings For [lobby] --------
[11:09:55] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:09:55] [Server thread/INFO]: Arrow Despawn Rate: 1200
[11:09:55] [Server thread/INFO]: Mob Spawn Range: 4
[11:09:55] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[11:09:55] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:09:55] [Server thread/INFO]: Cactus Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Cane Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Melon Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Sapling Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Wheat Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Vine Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[11:09:55] [Server thread/INFO]: Structure Info Saving: true
[11:09:55] [Server thread/INFO]: Max TNT Explosions: 100
[11:09:55] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[11:09:55] [Server thread/INFO]: Random Lighting Updates: false
[11:09:55] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[11:09:55] [Server thread/INFO]: Item Merge Radius: 2.5
[11:09:55] [Server thread/INFO]: Item Despawn Rate: 6000
[11:09:55] [Server thread/INFO]: Experience Merge Radius: 3.0
[11:09:55] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[11:09:55] [Server thread/INFO]: View Distance: 10
[11:09:55] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[11:09:55] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[11:09:56] [Server thread/INFO]: Preparing start region for level 0 (Seed: -571759862797639642)
[11:09:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:09:56] [Server thread/INFO]: Done (0,915s)! For help, type "help" or "?"
[11:09:56] [Server thread/INFO]: Starting GS4 status listener
[11:09:56] [Query Listener #1/INFO]: Query running on 0.0.0.0:25566
[11:09:56] [Server thread/INFO]: Stopping server
[11:09:56] [Server thread/INFO]: [ProtocolSupport] Disabling ProtocolSupport v4.25
[11:09:56] [Server thread/INFO]: Saving players
[11:09:56] [Server thread/INFO]: Saving worlds
[11:09:56] [Server thread/INFO]: Saving chunks for level 'lobby'/overworld
```

**Comment by Shevchik** [comment]
Latest dev build supports 1.12.
