### ISSUE TITLE
NullPointerException at ProtocolStorage.java:32

### ISSUE THREAD

**Issue by utkabobr** [ProtocolSupport/ProtocolSupport#563]
[13:29:32] [Server thread/ERROR]: Could not pass event EntityDamageEvent to ProtocolSupport v4.26.dev
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-latest.jar:git-Paper-1150]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:566) [PaperSpigot-latest.jar:git-Paper-1150]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1360) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:880) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.Entity.Y(Entity.java:452) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:200) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityInsentient.Y(EntityInsentient.java:188) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:333) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1888) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:248) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1749) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1719) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1536) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [PaperSpigot-latest.jar:git-Paper-1150]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [PaperSpigot-latest.jar:git-Paper-1150]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_111]
	at protocolsupport.protocol.storage.ProtocolStorage.getConnection(ProtocolStorage.java:32) ~[?:?]
	at protocolsupport.api.ProtocolSupportAPI.getConnection(ProtocolSupportAPI.java:68) ~[?:?]
	at protocolsupport.api.ProtocolSupportAPI.getConnection(ProtocolSupportAPI.java:58) ~[?:?]
	at protocolsupport.listeners.FeatureEmulation.onEntityDamage(FeatureEmulation.java:78) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor10.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-latest.jar:git-Paper-1150]
	... 27 more
Spamming with that error with Citizens installed

**Comment by Shevchik** [comment]
Should be fixed now
