### ISSUE TITLE
Small question for you related to async task

### ISSUE THREAD

**Issue by maxlehot1234** [ProtocolSupport/ProtocolSupport#569]
Hi, I install LagMonitor and this what I see: https://pastebin.com/b4M8t0uh

Is it possible to run it async instead of the main thread?

Thank you and have a nice day/night

**Comment by Shevchik** [comment]
It's not protocolsupport who performs this task.

**Comment by maxlehot1234** [comment]
@Shevchik So what is this in the error:
`        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:116) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:75) [ProtocolSupport.jar:?]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70) [ProtocolSupport.jar:?]`

**Comment by 7kasper** [comment]
@maxlehot1234 It isn't an error. LagMonitor detects that SkinRestorer is holding a thread. (It needs to, to apply custom skins)

**Comment by Shevchik** [comment]
It doesn't use the protocolsupport, the protocolsupport is in the log because it injects custom login handler.
