### ISSUE TITLE
Massive error on login

### ISSUE THREAD

**Issue by KingGoldensPanda** [ProtocolSupport/ProtocolSupport#573]
https://hastebin.com/kunurigegu.md

`
[19:33:41 INFO]: JustV_[/######] logged in with entity id 6616 at ([Vault]287.9815843368969, 74.0, 170.89935787635264)
[19:33:42 WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.07.22 at 18:30:47 MSK, buildhost: build.true-games.org, buildnumber: 97)): Network exception occured(address: /67.174.1.166:47511, username: NotAFatWhiteKid, version: MINECRAFT_1_12)
[19:33:42 WARN]:        at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:57)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.exceptionCaught(ChannelInjector.java:404)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[19:33:42 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[19:33:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[19:33:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:914)
[19:33:42 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:778)
[19:33:42 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1005)
[19:33:42 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
[19:33:42 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
[19:33:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[19:33:42 WARN]:        at java.lang.Thread.run(Thread.java:745)
[19:33:42 WARN]: Caused by: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
[19:33:42 WARN]:        at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
[19:33:42 INFO]: NotAFatWhiteKid lost connection: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.07.22 at 18:30:47 MSK, buildhost: build.true-games.org, buildnumber: 97)): Network exception occured(address: /67.174.1.166:47511, username: NotAFatWhiteKid, version: MINECRAFT_1_12)
[19:33:42 INFO]: The_Corruptor issued server command: /pick`

**Comment by Shevchik** [comment]
Disable debug
