### ISSUE TITLE
ProtocolSupport with spigot 1.11.2 

### ISSUE THREAD

**Issue by Kiwis2451** [ProtocolSupport/ProtocolSupport#629]
pls help me , my server is 1.11.2 , and I use ProtocolSupport v4.25
when i use 1.8.8 to login server , console appears the error , this error too many so i cannot post on anywhere. This is only a part of the error, it just keeps repeating this

`[07:07:01] [Netty Server IO #1/WARN]: java.lang.NoSuchMethodError: protocolsupport.api.ProtocolVersion.getProtocolType()Lprotocolsupport/api/ProtocolType;
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupportlegacysupport.hologram.HologramHandler.lambda$1(HologramHandler.java:40)
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.ConnectionImpl.handlePacketSend(ConnectionImpl.java:76)
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:45)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[07:07:01] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[07:07:01] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
[07:07:01] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:330)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[07:07:01] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[07:07:01] [Netty Server IO #1/WARN]: Error occured while handling packet sending
[07:07:01] [Netty Server IO #1/WARN]: java.lang.NoSuchMethodError: protocolsupport.api.ProtocolVersion.getProtocolType()Lprotocolsupport/api/ProtocolType;
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupportlegacysupport.bossbar.BossBarHandler.lambda$3(BossBarHandler.java:50)
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.ConnectionImpl.handlePacketSend(ConnectionImpl.java:76)
[07:07:01] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:45)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[07:07:01] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[07:07:01] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
[07:07:01] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:330)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[07:07:01] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[07:07:01] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Shevchik** [comment]
We are not supporting not latest dev build.
