### ISSUE TITLE
Exception in thread "StatusProcessingThread" 

### ISSUE THREAD

**Issue by MrSpock78** [ProtocolSupport/ProtocolSupport#652]
Had this warning a few times today. Not sure how to replicate.

```
[16:33:45 WARN]: Exception in thread "StatusProcessingThread" 
[16:33:45 WARN]: java.lang.NullPointerException
[16:33:45 WARN]:        at protocolsupport.protocol.pipeline.version.v_legacy.LegacyLoginAndPingHandler.lambda$writePing$0(LegacyLoginAndPingHandler.java:55)
[16:33:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:33:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:33:45 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Paper: 1.12.1 (# 1192)
ProtocolSupport: Version 4.4.0 snapshot b385 (# 138)

**Comment by Shevchik** [comment]
Software that wanted to ping the server disconnected before actually receiving ping data. Should be easily fixable.

**Comment by Shevchik** [comment]
Should be fixed now
