### ISSUE TITLE
When accessing the server you are kicked

### ISSUE THREAD

**Issue by xXTsunami72Xx** [ProtocolSupport/ProtocolSupport#693]
Hi, I use the latest version of protocolsupport - jenkins, spigot 1.12.1 buildtools, and bungeecord by HexagonMC.

I hope this can be solved, this only happens to me in 1.12 since I have servers with 1.11 and protocolsupport and they work well.

Greetings!!

**console error:**
`[13:48:44] [Server thread/INFO]: _xTsunamix_[/62.210.168.165:52448] logged in with entity id 399 at ([world]1547.3698408500845, 65.0, 847.9834125110273)
[13:48:45] [Netty Epoll Server IO #0/WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.09.18 at 17:36:55 MSK, buildhost: build.true-games.org, buildnumber: 161)): Network exception occured(address: /62.210.168.165:52448, username: _xTsunamix_, version: MINECRAFT_1_8)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:62)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1326)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:923)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:206)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:48:45] [Netty Epoll Server IO #0/WARN]: Caused by: io.netty.handler.codec.EncoderException: Unable to transform or read middle packet protocolsupport.protocol.packet.middleimpl.clientbound.play.v_8_9r1_9r2_10_11_12r1_12r2.KeepAlive(keepAliveId: 0, connection: protocolsupport.protocol.ConnectionImpl(player: CraftPlayer{name=_xTsunamix_}, address: /62.210.168.165:52448, rawaddress: /198.12.70.59:52448, version: MINECRAFT_1_8, metadata: {}), cache: protocolsupport.protocol.storage.NetworkDataCache(x: 1547.3698408500845, y: 65.0, z: 847.9834125110273, teleportConfirmId: 2, windowType: PLAYER, watchedEntities: {399=protocolsupport.protocol.utils.types.NetworkEntity(uuid: null, id: 399, type: PLAYER, cache: protocolsupport.protocol.utils.types.NetworkEntity$DataCache(firstMeta: false, baseMetaFlags: 0))}, player: protocolsupport.protocol.utils.types.NetworkEntity(uuid: null, id: 399, type: PLAYER, cache: protocolsupport.protocol.utils.types.NetworkEntity$DataCache(firstMeta: false, baseMetaFlags: 0)), playerlist: {b9def54a-c740-4e54-be44-181e567b46d7=protocolsupport.protocol.storage.NetworkDataCache$PlayerListEntry(name: _xTsunamix_, displayNameJson: null, propstorage: protocolsupport.protocol.storage.NetworkDataCache$PropertiesStorage(signed: {textures=protocolsupport.api.events.PlayerPropertiesResolveEvent$ProfileProperty@2b135ce1}, unsigned: {}))}, dimensionId: OVERWORLD, maxHealth: 20.0, locale: es_mx, keepAliveId: 0)) (data: [31, -7, -22, -17, -22, 2])
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:62)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:24)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:37)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:56)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1041)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	... 5 more
[13:48:45] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(6): PooledUnsafeDirectByteBuf(ridx: 1, widx: 6, cap: 256)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.packet.middle.clientbound.play.MiddleKeepAlive.readFromServerData(MiddleKeepAlive.java:12)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:49)
[13:48:45] [Netty Epoll Server IO #0/WARN]: 	... 26 more
[13:48:45] [Server thread/INFO]: _xTsunamix_ lost connection: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.09.18 at 17:36:55 MSK, buildhost: build.true-games.org, buildnumber: 161)): Network exception occured(address: /62.210.168.165:52448, username: _xTsunamix_, version: MINECRAFT_1_8)
[13:48:46] [Server thread/INFO]: _xTsunamix_ left the game`

**Comment by Shevchik** [comment]
The latest protocolsupport is for 1.12.2
