### ISSUE TITLE
client crash with 1.7

### ISSUE THREAD

**Issue by PhanaticD** [ProtocolSupport/ProtocolSupport#729]
not sure what is going on here but I get this client crash when using 1.7.10 

```
java.lang.IndexOutOfBoundsException: Index: 46, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at zs.a(SourceFile:104)
	at zs.a(SourceFile:385)
	at bjb.a(SourceFile:727)
	at gq.a(SourceFile:27)
	at gq.a(SourceFile:10)
	at ej.a(SourceFile:174)
	at bje.e(SourceFile:212)
	at bao.p(SourceFile:1306)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
```

**Comment by Shevchik** [comment]
Unable to reproduce under normal conditions, try finding out when and how it happens.
