### ISSUE TITLE
LagMonitor Hint

### ISSUE THREAD

**Issue by xXSchrandXx** [ProtocolSupport/ProtocolSupport#775]
Hey, I got a hint from an other plugin for you:
`[17:32:17] [Server thread/WARN]: [LagMonitor] Plugin ProtocolSupport is performing a blocking action on the main thread. This could be a performance hit Socket: http://mc.4creation.pro/dtlTraders/version.php. Such actions should be handled async from the main thread. Report it to the plugin author
[17:32:17] [Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
java.lang.IllegalAccessException: null
	at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:55) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:42) [LagMonitor.jar:?]
	at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) [LagMonitor.jar:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150) [?:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) [?:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) [?:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) [?:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) [?:1.8.0_151]
	at java.net.URL.openStream(URL.java:1045) [?:1.8.0_151]
	at net.dandielo.citizens.traders_v3.bukkit.DtlTraders.readJsonFromUrl(DtlTraders.java:312) [dtlTraders.jar:?]
	at net.dandielo.citizens.traders_v3.bukkit.DtlTraders.onPlayerJoin(DtlTraders.java:284) [dtlTraders.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:132) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:94) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

Link to the plugin GitHub-page: https://github.com/games647/LagMonitor

**Comment by WesleyVanNeck** [comment]
well i dont realy care if lags and you

**Comment by MrPowerGamerBR** [comment]
```
[?:1.8.0_151] at java.net.URL.openStream(URL.java:1045) [?:1.8.0_151] at net.dandielo.citizens.traders_v3.bukkit.DtlTraders.readJsonFromUrl(DtlTraders.java:312) [dtlTraders.jar:?] at net.dandielo.citizens.traders_v3.bukkit.DtlTraders.onPlayerJoin(DtlTraders.java:284) [dtlTraders.jar:?] 
```

Not ProtocolSupport issue

**Comment by MrPowerGamerBR** [comment]
Also, next time please wrap the stacktraces between ```, it makes the line breaks *work* instead of being all messy.

(well now that I'm thinking about it I hope it isn't a ProtocolSupport issue lol) but it seems Denizen is doing HTTP requests in the main thread, which isn't a good idea.

**Comment by MrPowerGamerBR** [comment]
Here's a related issue: https://github.com/ProtocolSupport/ProtocolSupport/issues/569
