### ISSUE TITLE
[1.7.2]client lost connection due to [java.lang.IndexOutOfBoundsExceptions]

### ISSUE THREAD

**Issue by collller** [ProtocolSupport/ProtocolSupport#81]
[1.7.2]client lost connection and show this message:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsExceptions: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)

**Comment by Shevchik** [comment]
Enable debug and post full stacktrace

**Comment by collller** [comment]
sorry i don't konw how to enable debug but i just test it in a new server and it happens when another player die

**Comment by collller** [comment]
i think it may be deathmessage problem

**Comment by collller** [comment]
[10:27:38 WARN]: java.lang.IllegalArgumentException: No enum constant net.md_5.bungee.api.chat.HoverEvent.Action.SHOW_ENTITY
[10:27:38 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[10:27:38 WARN]:        at net.md_5.bungee.api.chat.HoverEvent$Action.valueOf(HoverEvent.java:16)
[10:27:38 WARN]:        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:71)
[10:27:38 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
[10:27:38 WARN]:        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17)
[10:27:38 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[10:27:38 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[10:27:38 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[10:27:38 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[10:27:38 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[10:27:38 WARN]:        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[10:27:38 WARN]:        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[10:27:38 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[10:27:38 WARN]:        at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:28)
[10:27:38 WARN]:        at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:16)
[10:27:38 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:868)
[10:27:38 WARN]:        at com.google.gson.Gson$1.deserialize(Gson.java:126)
[10:27:38 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:60)
[10:27:38 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[10:27:38 WARN]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:768)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:717)
[10:27:38 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:689)
[10:27:38 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:34)
[10:27:38 WARN]:        at protocolsupport.protocol.transformer.v_1_7.utils.ChatJsonConverter.convert(ChatJsonConverter.java:20)
[10:27:38 WARN]:        at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:86)
[10:27:38 WARN]:        at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:61)
[10:27:38 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[10:27:38 WARN]:        at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[10:27:38 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:27:38 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[10:27:38 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[10:27:38 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[10:27:38 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[10:27:38 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[10:27:38 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[10:27:38 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[10:27:38 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[10:27:38 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[10:27:38 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:27:38 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:27:38 ERROR]: java.lang.IllegalArgumentException: No enum constant net.md_5.bungee.api.chat.HoverEvent.Action.SHOW_ENTITY

**Comment by Shevchik** [comment]
Are you sure that you are using latest build?

**Comment by collller** [comment]
i just download #255 and remove all other plugin test again and it still happen
btw, i use paperspigot

**Comment by Shevchik** [comment]
Should be fixed now
