### ISSUE TITLE
ProtocolSupport warn (?)

### ISSUE THREAD

**Issue by andris155** [ProtocolSupport/ProtocolSupport#82]
[20:14:38] [Server thread/INFO]: [+] Kagome
[20:14:38] [File IO Thread/WARN]: java.io.IOException: Stream Closed
[20:14:38] [File IO Thread/WARN]: 	at java.io.RandomAccessFile.seek0(Native Method)
[20:14:38] [File IO Thread/WARN]: 	at java.io.RandomAccessFile.seek(Unknown Source)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.RegionFile.a(RegionFile.java:255)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.RegionFile.a(RegionFile.java:192)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.RegionFile$ChunkBuffer.close(RegionFile.java:304)
[20:14:38] [File IO Thread/WARN]: 	at java.util.zip.DeflaterOutputStream.close(Unknown Source)
[20:14:38] [File IO Thread/WARN]: 	at java.io.FilterOutputStream.close(Unknown Source)
[20:14:38] [File IO Thread/WARN]: 	at java.io.FilterOutputStream.close(Unknown Source)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.b(ChunkRegionLoader.java:180)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.c(ChunkRegionLoader.java:161)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:35)
[20:14:38] [File IO Thread/WARN]: 	at net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28)
[20:14:38] [File IO Thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by MrPowerGamerBR** [comment]
Does ProtocolSupport even change the loading method for worlds? I think it only changes the world after it was loaded, not when loading.
