### ISSUE TITLE
When open SHULKER_BOX, IndexOutOfBoundsException before minecraft 1.11

### ISSUE THREAD

**Issue by mckite** [ProtocolSupport/ProtocolSupport#844]
When open the SHULKER_BOX before MC 1.11, the error occures in client.
( java.lang.IndexOutOfBoundsException)
COnsole:
[18:58:19 INFO]: Enabled debug
[18:58:21 INFO]: [ProtocolSupport] /127.0.0.1:30456 connected with protocol version MINECRAFT_1_7_10
[18:58:24 INFO]: [ProtocolSupport] /127.0.0.1:30462 connected with protocol version MINECRAFT_1_7_10
[18:58:25 INFO]: [ProtocolSupport] /127.0.0.1:30464 connected with protocol version MINECRAFT_1_7_10
[18:58:25 INFO]: [Nobuguppercase] User join with nick: [KitePro]
[18:58:25 INFO]: UUID of player KitePro is 14ad8dfa-3cc7-3c22-8430-a84c63b7ee55
[18:58:26 INFO]: KitePro[/127.0.0.1:30464] logged in with entity id 545 at ([world]-1212.300000011921, 37.0, -1201.9149801952879)

[18:58:28 INFO]: [AuthMe] KitePro logged in!
[18:58:28 INFO]: KitePro lost connection: Disconnected
[18:58:28 INFO]: KitePro 님이 Kite서버에서 퇴장하셨습니다.
>ps debug
[18:58:34 INFO]: Disabled debug
[18:58:41 INFO]: /127.0.0.1:30456 lost connection: Disconnected

Client:
etworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(19) + length(4) exceeds writerIndex(19): UnpooledHeapByteBuf(ridx: 19, widx: 19, cap: 19)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(19) + length(4) exceeds writerIndex(19): UnpooledHeapByteBuf(ridx: 19, widx: 19, cap: 19)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160)
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:611)
	at net.minecraft.network.PacketBuffer.readInt(SourceFile:526)
	at net.minecraft.network.play.server.S2DPacketOpenWindow.func_148837_a(SourceFile:62)
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
	... 16 more

**Comment by mckite** [comment]
But, In 1.5.2, can't open that instead of OutBoundError

**Comment by mckite** [comment]
[20:34:44 WARN]: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
[20:34:44 WARN]:        at sun.nio.ch.SocketDispatcher.write0(Native Method)
[20:34:44 WARN]:        at sun.nio.ch.SocketDispatcher.write(Unknown Source)
[20:34:44 WARN]:        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
[20:34:44 WARN]:        at sun.nio.ch.IOUtil.write(Unknown Source)
[20:34:44 INFO]: KitePro lost connection: Disconnected
[20:34:44 WARN]:        at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
[20:34:44 WARN]:        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:403)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
[20:34:44 WARN]:        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
[20:34:44 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
[20:34:44 WARN]:        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[20:34:44 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[20:34:44 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:34:44 INFO]: KitePro 님이 Kite서버에서 퇴장하셨습니다.
[20:34:44 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200)
[20:34:44 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:330)
[20:34:44 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[20:34:44 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[20:34:44 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[20:34:44 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[20:34:44 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:34:44 WARN]: java.nio.channels.ClosedChannelException
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[20:34:44 WARN]: java.nio.channels.ClosedChannelException
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[20:34:44 WARN]: java.nio.channels.ClosedChannelException
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[20:34:44 WARN]: java.nio.channels.ClosedChannelException
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[20:34:44 WARN]: java.nio.channels.ClosedChannelException
[20:34:44 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
