### ISSUE TITLE
NPE in PlayerList.java

### ISSUE THREAD

**Issue by kamcio96** [ProtocolSupport/ProtocolSupport#852]
Hi!
```
[13:42:48 WARN]: Failed to handle packet for /X.X.X.X:55978
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:142) ~[patched_1.12.2.jar:git-Paper-1497]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:123) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:125) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:87) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:69) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.12.2.jar:git-Paper-1497]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1497]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:947) [patched_1.12.2.jar:git-Paper-1497]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1497]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [patched_1.12.2.jar:git-Paper-1497]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1497]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

```
[13:46:14 INFO]: This server is running Paper version git-Paper-1497 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:46:14 INFO]: Previous version: git-Paper-1446 (MC: 1.12.2)
[13:46:14 INFO]: Checking version, please wait...
[13:46:14 INFO]: You are running the latest version
> ver ProtocolSupport
[13:46:22 INFO]: ProtocolSupport version 4.29-dev
[13:46:22 INFO]: Authors: _Shevchik_, 7kasper, MrPowerGamerBR and gdude2002
```

**Comment by kamcio96** [comment]
Plugin and server issue. Will create PR with warning to spigot.
