### ISSUE TITLE
NettyChannelInjector.decode() did not read anything but decoded a message.

### ISSUE THREAD

**Issue by andris155** [ProtocolSupport/ProtocolSupport#86]
[16:46:24] [Netty Server IO #0/WARN]: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:46:24] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[16:46:24] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:46:24] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:46:25] [Server thread/INFO]: Google lost connection: Internal Exception: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
[16:46:25] [Server thread/INFO]: [-] Google

**Comment by Shevchik** [comment]
Still not enough info, protocolsupport is not even in the stacktrace which means it wasnt injected into the pipeline for whatever reason. Remove your plugins one by one and try to reproduce this again.

**Comment by andris155** [comment]
Plugin removed my server.

**Comment by sgdc3** [comment]
...

**Comment by DardBrinza** [comment]
Where fix? My error:
player lost connection: Internal Exception: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
