### ISSUE TITLE
IllegalStateException during onEnable of ProtocolSupport.

### ISSUE THREAD

**Issue by Unknowncmbk** [ProtocolSupport/ProtocolSupport#865]
When the plugin starts up an illegal state exception occurs:

```
[20:27:52] [Server thread/ERROR]: Error occurred while enabling ProtocolSupport v4.29-dev (Is it up to date?)
java.lang.IllegalStateException: Access to implementation before detect
	at protocolsupport.zplatform.ServerPlatform.get(ServerPlatform.java:37) ~[?:?]
	at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:135) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paperclip.jar:git-Paper-1268]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [paperclip.jar:git-Paper-1268]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [paperclip.jar:git-Paper-1268]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [paperclip.jar:git-Paper-1268]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [paperclip.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) [paperclip.jar:git-Paper-1268]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [paperclip.jar:git-Paper-1268]
```

which refers to:
```
ServerPlatform.get().getInjector().onEnable();
```
and then calls:
```
public static ServerPlatform get() {
		if (current == null) {
			throw new IllegalStateException("Access to implementation before detect");
		}
		return current;
	}
```

Solution:
- Call ServerPlatform.detect().

**Comment by MrPowerGamerBR** [comment]
**Solution:**
* Update your server to 1.13, the latest Jenkins build is only for 1.13.
