### ISSUE TITLE
1.13.1 Crash (java.lang.IllegalStateException: Access to implementation before detect)

### ISSUE THREAD

**Issue by Rpg-paradise** [ProtocolSupport/ProtocolSupport#880]
Error when starting server on Last spigot 1.13.1
Update needed :)

`[12:39:55] [Server thread/ERROR]: Error occurred while enabling ProtocolSupport v4.29-dev (Is it up to date?)
java.lang.IllegalStateException: Access to implementation before detect
	at protocolsupport.zplatform.ServerPlatform.get(ServerPlatform.java:37) ~[?:?]
	at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:136) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [OpenMod-Prov2.jar:git-Spigot-2440e18-908516f]
	at java.lang.Thread.run(Thread.java:844) [?:?]`

**Comment by Remu-2018** [comment]
Yeah not supported yet

**Comment by Remu-2018** [comment]
Use 1.13
