### ISSUE TITLE
ProtocolSupport Say to me, I have a Error!

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupport#89]
[04:49:38] [Netty Server IO #2/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[04:49:38] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[04:49:38] [Netty Server IO #2/WARN]: 	at protocolsupport.protocol.core.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:129)
[04:49:38] [Netty Server IO #2/WARN]: 	at protocolsupport.protocol.core.initial.Ping152ResponseTask.run(Ping152ResponseTask.java:19)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[04:49:38] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[04:49:38] [Netty Server IO #2/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[04:49:38] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[04:49:38] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:541)
[04:49:38] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[04:49:38] [Netty Server IO #2/WARN]: 	... 17 more
[04:49:38] [Netty Server IO #2/WARN]: Caused by: java.io.IOException: Can't deserialize unknown packet 10
[04:49:38] [Netty Server IO #2/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:51)
[04:49:38] [Netty Server IO #2/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:28)
[04:49:38] [Netty Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
[04:49:38] [Netty Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[04:49:38] [Netty Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[04:49:38] [Netty Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[04:49:38] [Netty Server IO #2/WARN]: 	... 19 more

Turn on PSdebug. console say that error

**Comment by Shevchik** [comment]
When and how this happens?

**Comment by swan201** [comment]
umm. That error just spaming console. That's all. (if turn on PS debug)
