### ISSUE TITLE
Client crash with pistons (1.12.2 on 1.13.2)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#901]
I have an automatic pumpkin farm with pistons - When the pistons are activated to push the pumpkins the 1.12.2 client crashes with the following exception:

[03:04:21] [main/FATAL]: Reported exception thrown!
f: Ticking block entity
	at amu.k(SourceFile:1432) ~[amu.class:?]
	at bib.t(SourceFile:1691) ~[bib.class:?]
	at bib.az(SourceFile:1000) ~[bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at magic.launcher.Launcher.main(SourceFile:214) [MagicLauncher.exe:?]

Caused by: java.lang.IllegalArgumentException: Cannot get property axg{name=facing, clazz=class fa, values=[down, up, north, south, west, east]} as it does not exist in awu{block=minecraft:air, properties=[]}
	at awu$a.c(BlockStateContainer.java:209) ~[awu$a.class:?]
	at awm.k(SourceFile:121) ~[awm.class:?]
	at awm.f(SourceFile:132) ~[awm.class:?]
	at awm.e(SourceFile:332) ~[awm.class:?]
	at amu.k(SourceFile:1424) ~[amu.class:?]
	... 15 more

**Comment by 7kasper** [comment]
Hey I am unable to reproduce this.. Can you show us a picture of your piston setup when this happens exactly?

**Comment by Brokkonaut** [comment]
I created a test world: https://www65.zippyshare.com/v/NMBAdEfi/file.html
There is a lever at -47 66 -232 You might have to toggle it serveral times until it crashes

**Comment by Brokkonaut** [comment]
This bug still exists https://pastebin.com/raw/tpN5747S (1.12.2 client on 1.13.2 server)

**Comment by Shevchik** [comment]
Reupload the test world please.

**Comment by Brokkonaut** [comment]
World: https://www5.zippyshare.com/v/XtyzhXN5/file.html
The lever is at -2942 100 -641

**Comment by Shevchik** [comment]
Somehow related to piston retract.

**Comment by Shevchik** [comment]
Huh, found the reason.
Since 1.9.2 the chunk data includes tile entity list.
Piston is tile entity, and it's the only one place where it is sent. (Everything else is controlled via BlockAction). And the tile itself contains a block id, which needs to be remapped now.
And the reason why it's hard to trigger is because a chunk update is needed, and it only happens if more than 16 blocks were updated in a chunk in a single tick.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by Brokkonaut** [comment]
thx
