### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by EazyFTW** [ProtocolSupport/ProtocolSupport#902]
Is it possible to fix the scoreboard when you're not using 1.13 (At Least it happens on 1.8). The scoreboard is bugged out. If it isn't it's fine, but if it is it would be nice if you would fix it, thanks.

**Comment by MrPowerGamerBR** [comment]
Can you share a few screenshots showing the bug?

**Comment by EazyFTW** [comment]
Yes one second, let me load up 1.8.9.

**Comment by EazyFTW** [comment]
Broken:
https://i.eazyftw.com/g8u4zPS

Normal:
https://i.eazyftw.com/tsBVseR

**Comment by MrPowerGamerBR** [comment]
Thank you!

By the way, does that happen with 1.12.2? I did notice that scoreboards are also kinda broken on my 1.13.1 server when connecting with any version that isn't 1.13+.

**Comment by EazyFTW** [comment]
No problem, I don't know if it breaks with 1.12.2. I'm guessing so as they changed some things with the sb in 1.13.

**Comment by Shevchik** [comment]
This is however normal. You have reached the maximum amount of symbols for < 1.13 versions (16 for prefix/suffix, 32 for title).

**Comment by EazyFTW** [comment]
However, it would work fine if I switched the server to 1.12.2 using the same plugin.

**Comment by MrPowerGamerBR** [comment]
@Shevchik would that happen even if you were using a plugin that worked fine in MC 1.12.2, but looks wonky in 1.13.1 + ProtocolSupport in a 1.12.2?

My scoreboard plugins used teams + offline players to have 48 symbols in the scoreboard, it worked fine in 1.12.2, but in 1.13.1 + ProtocolSupport it looks cut off when connecting with any client before 1.13.

**Comment by sgdc3** [comment]
This is how i fixed it with a simple plugin: https://github.com/FearGames/CommonUtilities/blob/master/src/main/java/it/feargames/commonutilities/module/implementation/fix/FixScoreboardProtocolSupport.java

**Comment by Shevchik** [comment]
Yeah, it still may happen. In never versions prefix/suffix/name are json chat components, so they need to be converted to legacy text first.
The json component converter adds and reset symbol after component change when converting to legacy text. I guess it can be improved to minimize the unneeded reset color codes.

**Comment by EazyFTW** [comment]
> This is how i fixed it with a simple plugin: https://github.com/FearGames/CommonUtilities/blob/master/src/main/java/it/feargames/commonutilities/module/implementation/fix/FixScoreboardProtocolSupport.java

```[06:57:01 INFO]: [CommonUtilities] Enabling CommonUtilities v2.1.1-SNAPSHOT
[06:57:01 ERROR]: Error occurred while enabling CommonUtilities v2.1.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at it.feargames.commonutilities.CommonUtilities.onEnable(CommonUtilities.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[06:57:01 INFO]: [CommonUtilities] Disabling CommonUtilities v2.1.1-SNAPSHOT
[06:57:01 ERROR]: Error occurred while disabling CommonUtilities v2.1.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at it.feargames.commonutilities.CommonUtilities.onDisable(CommonUtilities.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]```

**Comment by EazyFTW** [comment]
I contacted the author and it has been fixed, now it works really nicely w/ 1.8.9! (Except the title, the color codes are still messed up :/.

**Comment by EazyFTW** [comment]
It would be nice if you could ask the author to put it in ProtocolSupport though :p

**Comment by zeronerve** [comment]
Hi @Shevchik . I'm struggling with this in 1.14.4 (with 1.8.9 clients) . Is there a better solution? I don't know how to implement the above module.
