### ISSUE TITLE
Cannot connect to ProtocolSupport backend server behind BungeeCord

### ISSUE THREAD

**Issue by zedwick** [ProtocolSupport/ProtocolSupport#952]
Attempting to join the 1.13.2 server running ProtocolSupport yields the same error with a 1.12.2, 1.13.1 and 1.13.2 client:

`17:15:49 [INFO] [Zedwick] <-> ServerConnector [Plugz] has connected
17:15:49 [SEVERE] [Zedwick] <-> ServerConnector [Plugz] - encountered exception java.lang.IllegalArgumentException: Unexpected packet received during server login process! 1ba6017b226578747261223a5b7b2274657874223a22227d2c7b2274657874223a22496e7465726e616c20457863657074696f6e3a206a6176612e6c616e672e
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:130)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at java.lang.Thread.run(Thread.java:745)
17:15:49 [INFO] [Zedwick] disconnected with: Exception Connecting:IllegalArgumentException : Unexpected packet received during server login process! 1ba6017b226578747261223a5b7b2274657874223a22227d2c7b2274657874223a22496e7465726e616c20457863657074696f6e3a206a6176612e6c616e672e @ net.md_5.bungee.ServerConnector:130`

This issue occurs with ProtocolSupport builds 311 and 314, but not build 310.
Bungeecord version: BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:1c5bff7:1359 by md_5

**Comment by i9hdkill** [comment]
Exact same error here. Forge or non Forge clients doesn't make a difference. Tested with 1.12.2 client

**Comment by Mgazul** [comment]
Encountered the same problem

**Comment by i9hdkill** [comment]
Spigot:
LuckPerms, NetCoins, WorldEdit, gReqBukkit, FirstJoinPlus, JumpPads, ResetResourcePack, ScheduledAnnouncer2, Chairs, WorldBorder, BlockSyntax, Marriage, WorldGuard, ProtocolLib, Emotes, EchoPet, PartyAndFriendsGUI, distributor-Spigot, CustomJoinItems, Vault, ProtocolSupport, boosCooldowns, TitleManager, geSuitPortals, UltraCosmetics, ClientStats, PwnFilter, HolographicDisplays, BuycraftX, geSuitBans, CommandSigns, Citizens, SignColors, ColoredTags, ChestCommands, geSuitTeleports, SimpleAlias, geSuitChat, CommandNPC, geSuitHomes, geSuitSpawn, geSuitWarps

Bungee:
http://prntscr.com/ljy9z9

**Comment by TheCompieter** [comment]
i have the same isseu too

**Comment by Xadzkon** [comment]
I have the same issue, tested with fresh / empty BungeeCord & Spigot without plugins. The issue does not happen if the server is Paper.

**Comment by Speentie8081** [comment]
Are you using ProtocolSupportBungee? You need to

**Comment by i9hdkill** [comment]
It was never needed and I don't see the reason to use it

**Comment by TheCompieter** [comment]
i never needed it and i cant even use because i have viaversion installed on my proxy

**Comment by pkt77** [comment]
Here's the stack trace when PS debug is enabled: https://pastebin.com/LkKtgySX

**Comment by Sckaletz** [comment]
Same problem here too.

**Comment by TheCompieter** [comment]
check the latest build please.

**Comment by TheCompieter** [comment]
!!!Its fixed in the latest dev build!!!

**Comment by Mgazul** [comment]
Just tested, the latest version #320, fixed the problem

**Comment by MWLVegas** [comment]
This appears to be happening still, or again, with build 324, 323, and 322. I have not yet tried with 321.

**Comment by TheCompieter** [comment]
jup its back again the bug
:(

**Comment by x1p** [comment]
I removed Protocolsupport, but I'm still suffering disconnects, impossible to connect and errors.
How do I get this protocol-virus off my server?

**Comment by x1p** [comment]
I had an error with a few protocol words in it. So I figured it would be protocolsupport.
Hmm. I have to eliminate a few things.

**Comment by TheCompieter** [comment]
latest build (326) fixed the isseu again
