### ISSUE TITLE
Not compatible with AlwaysOnline

### ISSUE THREAD

**Issue by Spurlex** [ProtocolSupport/ProtocolSupport#98]
Hi,

When the auth servers go down usually AlwaysOnline kicks in and allows users to join (https://github.com/johnnywoof/AlwaysOnline)

This plugin errors in Bungee 

```
19:21:27 [WARNING] [AlwaysOnline] Internal error for Macchiatos, preventing login.
19:21:27 [SEVERE] java.lang.NoSuchFieldException: uniqueId
19:21:27 [SEVERE]     at java.lang.Class.getDeclaredField(Class.java:2070)
19:21:27 [SEVERE]     at me.johnnywoof.bungee.AOListener.onPost(AOListener.java:160)
19:21:27 [SEVERE]     at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
19:21:27 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:21:27 [SEVERE]     at java.lang.reflect.Method.invoke(Method.java:497)
19:21:27 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
19:21:27 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
19:21:27 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
19:21:27 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:491)
19:21:27 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
19:21:27 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
19:21:27 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
19:21:27 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
```

**Comment by Shevchik** [comment]
Not possible to fix that on ProtocolSupport side. Also this is not a ProtocolSupportBungee repository.
